//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TGV.IPEFAE.Web.Resources.Admin.Concurso.Inscrito {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TGV.IPEFAE.Web.Resources.Admin.Concurso.Inscrito.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pesquisar.
        /// </summary>
        public static string BotaoPesquisar {
            get {
                return ResourceManager.GetString("BotaoPesquisar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clique para visualizar mais inscritos.
        /// </summary>
        public static string CliqueVisualizar {
            get {
                return ResourceManager.GetString("CliqueVisualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opção.
        /// </summary>
        public static string ColunaCargos {
            get {
                return ResourceManager.GetString("ColunaCargos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPF.
        /// </summary>
        public static string ColunaCPF {
            get {
                return ResourceManager.GetString("ColunaCPF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inscrição.
        /// </summary>
        public static string ColunaDataInscricao {
            get {
                return ResourceManager.GetString("ColunaDataInscricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Isento.
        /// </summary>
        public static string ColunaIsento {
            get {
                return ResourceManager.GetString("ColunaIsento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string ColunaNome {
            get {
                return ResourceManager.GetString("ColunaNome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nº Inscr..
        /// </summary>
        public static string ColunaNroMatricula {
            get {
                return ResourceManager.GetString("ColunaNroMatricula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string ColunaStatus {
            get {
                return ResourceManager.GetString("ColunaStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor Pago.
        /// </summary>
        public static string ColunaValorPago {
            get {
                return ResourceManager.GetString("ColunaValorPago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ativo.
        /// </summary>
        public static string LabelFiltroAtivo {
            get {
                return ResourceManager.GetString("LabelFiltroAtivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPF.
        /// </summary>
        public static string LabelFiltroCPF {
            get {
                return ResourceManager.GetString("LabelFiltroCPF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Isento.
        /// </summary>
        public static string LabelFiltroIsento {
            get {
                return ResourceManager.GetString("LabelFiltroIsento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matrícula.
        /// </summary>
        public static string LabelFiltroMatricula {
            get {
                return ResourceManager.GetString("LabelFiltroMatricula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string LabelFiltroNome {
            get {
                return ResourceManager.GetString("LabelFiltroNome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + Adicionar Inscrito.
        /// </summary>
        public static string LinkAdicionarInscrito {
            get {
                return ResourceManager.GetString("LinkAdicionarInscrito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;- Voltar.
        /// </summary>
        public static string LinkVoltar {
            get {
                return ResourceManager.GetString("LinkVoltar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carregando lista de inscritos....
        /// </summary>
        public static string MensagemCarregando {
            get {
                return ResourceManager.GetString("MensagemCarregando", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gerando boleto ....
        /// </summary>
        public static string MensagemGerandoBoleto {
            get {
                return ResourceManager.GetString("MensagemGerandoBoleto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhum inscrito foi encontrado.
        /// </summary>
        public static string NenhumInscritoEncontrado {
            get {
                return ResourceManager.GetString("NenhumInscritoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ativo.
        /// </summary>
        public static string OptionAtivo {
            get {
                return ResourceManager.GetString("OptionAtivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inativo.
        /// </summary>
        public static string OptionInativo {
            get {
                return ResourceManager.GetString("OptionInativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Isento.
        /// </summary>
        public static string OptionIsento {
            get {
                return ResourceManager.GetString("OptionIsento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pagante.
        /// </summary>
        public static string OptionPagante {
            get {
                return ResourceManager.GetString("OptionPagante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todos.
        /// </summary>
        public static string OptionTodos {
            get {
                return ResourceManager.GetString("OptionTodos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ativo.
        /// </summary>
        public static string StatusAtivo {
            get {
                return ResourceManager.GetString("StatusAtivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inativo.
        /// </summary>
        public static string StatusInativo {
            get {
                return ResourceManager.GetString("StatusInativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Isento.
        /// </summary>
        public static string StatusIsento {
            get {
                return ResourceManager.GetString("StatusIsento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pagante.
        /// </summary>
        public static string StatusNaoIsento {
            get {
                return ResourceManager.GetString("StatusNaoIsento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista de inscritos neste concurso.
        /// </summary>
        public static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gerar boleto.
        /// </summary>
        public static string TitleBoleto {
            get {
                return ResourceManager.GetString("TitleBoleto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar dados.
        /// </summary>
        public static string TitleEditar {
            get {
                return ResourceManager.GetString("TitleEditar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualizar estatisticas do concurso.
        /// </summary>
        public static string TitleEstatisticas {
            get {
                return ResourceManager.GetString("TitleEstatisticas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gerenciar inscritos.
        /// </summary>
        public static string TitleGerenciarInscritos {
            get {
                return ResourceManager.GetString("TitleGerenciarInscritos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualizar recursos.
        /// </summary>
        public static string TitleRecursos {
            get {
                return ResourceManager.GetString("TitleRecursos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gerenciar Inscrições.
        /// </summary>
        public static string TituloTela {
            get {
                return ResourceManager.GetString("TituloTela", resourceCulture);
            }
        }
    }
}
