//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TGV.IPEFAE.Web.Resources.Admin.Concurso {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class _ListaCargosDisponiveis {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _ListaCargosDisponiveis() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TGV.IPEFAE.Web.Resources.Admin.Concurso._ListaCargosDisponiveis", typeof(_ListaCargosDisponiveis).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ativo?.
        /// </summary>
        public static string ColunaAtivo {
            get {
                return ResourceManager.GetString("ColunaAtivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opção.
        /// </summary>
        public static string ColunaNomeCargo {
            get {
                return ResourceManager.GetString("ColunaNomeCargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor Inscrição.
        /// </summary>
        public static string ColunaValorInscricao {
            get {
                return ResourceManager.GetString("ColunaValorInscricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alterando ativação do opção....
        /// </summary>
        public static string MensagemDesativando {
            get {
                return ResourceManager.GetString("MensagemDesativando", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhuma opção encontrada.
        /// </summary>
        public static string NenhumCargoEncontrado {
            get {
                return ResourceManager.GetString("NenhumCargoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operação realizada com sucesso....
        /// </summary>
        public static string OperacaoMensagemSucesso {
            get {
                return ResourceManager.GetString("OperacaoMensagemSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ativar opção.
        /// </summary>
        public static string TitleAtivar {
            get {
                return ResourceManager.GetString("TitleAtivar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desativar opção.
        /// </summary>
        public static string TitleDesativar {
            get {
                return ResourceManager.GetString("TitleDesativar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        public static string TitleEditar {
            get {
                return ResourceManager.GetString("TitleEditar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluir.
        /// </summary>
        public static string TitleExcluir {
            get {
                return ResourceManager.GetString("TitleExcluir", resourceCulture);
            }
        }
    }
}
