//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TGV.IPEFAE.Web.Resources.Admin.Concurso {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class _ModalAnexosConcurso {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _ModalAnexosConcurso() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TGV.IPEFAE.Web.Resources.Admin.Concurso._ModalAnexosConcurso", typeof(_ModalAnexosConcurso).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formato do arquivo inválido (PDF, DOC ou DOCX).
        /// </summary>
        public static string ArquivoFormatoInvalido {
            get {
                return ResourceManager.GetString("ArquivoFormatoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O arquivo é obrigatório.
        /// </summary>
        public static string ArquivoObrigatorio {
            get {
                return ResourceManager.GetString("ArquivoObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvar.
        /// </summary>
        public static string BotaoAdicionar {
            get {
                return ResourceManager.GetString("BotaoAdicionar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        public static string BotaoCancelar {
            get {
                return ResourceManager.GetString("BotaoCancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de início do recurso com formato inválido.
        /// </summary>
        public static string DataInicioFormatoInvalido {
            get {
                return ResourceManager.GetString("DataInicioFormatoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de início do recurso é obrigatória.
        /// </summary>
        public static string DataInicioObrigatorio {
            get {
                return ResourceManager.GetString("DataInicioObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de publicação com formato inválido.
        /// </summary>
        public static string DataPublicacaoFormatoInvalido {
            get {
                return ResourceManager.GetString("DataPublicacaoFormatoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de publicação é obrigatória.
        /// </summary>
        public static string DataPublicacaoObrigatorio {
            get {
                return ResourceManager.GetString("DataPublicacaoObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de término do recurso com formato inválido.
        /// </summary>
        public static string DataTerminoFormatoInvalido {
            get {
                return ResourceManager.GetString("DataTerminoFormatoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de término do recurso é obrigatória.
        /// </summary>
        public static string DataTerminoObrigatorio {
            get {
                return ResourceManager.GetString("DataTerminoObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arquivo.
        /// </summary>
        public static string LabelArquivo {
            get {
                return ResourceManager.GetString("LabelArquivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Término Recurso (Data e Hora).
        /// </summary>
        public static string LabelDataFimRecurso {
            get {
                return ResourceManager.GetString("LabelDataFimRecurso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Início Recurso (Data e Hora).
        /// </summary>
        public static string LabelDataInicioRecurso {
            get {
                return ResourceManager.GetString("LabelDataInicioRecurso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publicar em  (Data e Hora).
        /// </summary>
        public static string LabelDataPublicacao {
            get {
                return ResourceManager.GetString("LabelDataPublicacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome Arquivo.
        /// </summary>
        public static string LabelNomeArquivo {
            get {
                return ResourceManager.GetString("LabelNomeArquivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tem Recurso?.
        /// </summary>
        public static string LabelTemRecurso {
            get {
                return ResourceManager.GetString("LabelTemRecurso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo.
        /// </summary>
        public static string LabelTipo {
            get {
                return ResourceManager.GetString("LabelTipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falha na realização do upload.
        /// </summary>
        public static string LabelUploadErro {
            get {
                return ResourceManager.GetString("LabelUploadErro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload realizado com sucesso.
        /// </summary>
        public static string LabelUploadSucesso {
            get {
                return ResourceManager.GetString("LabelUploadSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operação realizada com sucesso.
        /// </summary>
        public static string MensagemArquivoAnexadoSucesso {
            get {
                return ResourceManager.GetString("MensagemArquivoAnexadoSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Realizando upload do arquivo ....
        /// </summary>
        public static string MensagemRealizandoUpload {
            get {
                return ResourceManager.GetString("MensagemRealizandoUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome do arquivo é obrigatório.
        /// </summary>
        public static string NomeArquivoObrigatorio {
            get {
                return ResourceManager.GetString("NomeArquivoObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não.
        /// </summary>
        public static string OptionNao {
            get {
                return ResourceManager.GetString("OptionNao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sim.
        /// </summary>
        public static string OptionSim {
            get {
                return ResourceManager.GetString("OptionSim", resourceCulture);
            }
        }
    }
}
