//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TGV.IPEFAE.Web.Resources.Admin.Concurso {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Cadastro {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Cadastro() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TGV.IPEFAE.Web.Resources.Admin.Concurso.Cadastro", typeof(Cadastro).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recurso aberto entre {0} e {1}.
        /// </summary>
        public static string AlertaRecurso {
            get {
                return ResourceManager.GetString("AlertaRecurso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Período Isenção aberto entre {0} e {1}.
        /// </summary>
        public static string AlertaRecursoIsencao {
            get {
                return ResourceManager.GetString("AlertaRecursoIsencao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adicionar.
        /// </summary>
        public static string AltImageAdicionar {
            get {
                return ResourceManager.GetString("AltImageAdicionar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvar.
        /// </summary>
        public static string BotaoSalvar {
            get {
                return ResourceManager.GetString("BotaoSalvar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voltar.
        /// </summary>
        public static string BotaoVoltar {
            get {
                return ResourceManager.GetString("BotaoVoltar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O formato da data de saída da aba encerramento está inválida.
        /// </summary>
        public static string DataEncerramentoFormatoInvalido {
            get {
                return ResourceManager.GetString("DataEncerramentoFormatoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O formato da data de encerramento das inscrições está inválida.
        /// </summary>
        public static string DataEncerramentoInscricoesFormatoInvalido {
            get {
                return ResourceManager.GetString("DataEncerramentoInscricoesFormatoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data de encerramento das inscrições é obrigatória.
        /// </summary>
        public static string DataEncerramentoInscricoesObrigatorio {
            get {
                return ResourceManager.GetString("DataEncerramentoInscricoesObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data de saída da aba encerramento é obrigatória.
        /// </summary>
        public static string DataEncerramentoObrigatorio {
            get {
                return ResourceManager.GetString("DataEncerramentoObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O formato da data de início das inscrições está inválida.
        /// </summary>
        public static string DataInicioFormatoInvalido {
            get {
                return ResourceManager.GetString("DataInicioFormatoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data de início das inscrições é obrigatória.
        /// </summary>
        public static string DataInicioObrigatorio {
            get {
                return ResourceManager.GetString("DataInicioObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A identificação (nome) do concurso é obrigatória.
        /// </summary>
        public static string IdentificacaoObrigatoria {
            get {
                return ResourceManager.GetString("IdentificacaoObrigatoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ativo.
        /// </summary>
        public static string LabelAtivo {
            get {
                return ResourceManager.GetString("LabelAtivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venc. Boleto (Data e Hora).
        /// </summary>
        public static string LabelDataBoleto {
            get {
                return ResourceManager.GetString("LabelDataBoleto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fim do Concurso (Data e Hora).
        /// </summary>
        public static string LabelDataEncerramento {
            get {
                return ResourceManager.GetString("LabelDataEncerramento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fim Cartão (Data e Hora).
        /// </summary>
        public static string LabelDataEncerramentoComprovante {
            get {
                return ResourceManager.GetString("LabelDataEncerramentoComprovante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fim Inscrições (Data e Hora).
        /// </summary>
        public static string LabelDataEncerramentoInscricoes {
            get {
                return ResourceManager.GetString("LabelDataEncerramentoInscricoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fim Isento (Data e Hora).
        /// </summary>
        public static string LabelDataEncerramentoIsento {
            get {
                return ResourceManager.GetString("LabelDataEncerramentoIsento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Início Inscrições (Data e Hora).
        /// </summary>
        public static string LabelDataInicio {
            get {
                return ResourceManager.GetString("LabelDataInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Início Class. (Data e Hora).
        /// </summary>
        public static string LabelDataInicioClassificacao {
            get {
                return ResourceManager.GetString("LabelDataInicioClassificacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Início Cartão (Data e Hora).
        /// </summary>
        public static string LabelDataInicioComprovante {
            get {
                return ResourceManager.GetString("LabelDataInicioComprovante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Início Isento (Data e Hora).
        /// </summary>
        public static string LabelDataInicioIsento {
            get {
                return ResourceManager.GetString("LabelDataInicioIsento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empresa - Boleto.
        /// </summary>
        public static string LabelEmpresa {
            get {
                return ResourceManager.GetString("LabelEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encerrar Concurso?.
        /// </summary>
        public static string LabelEncerrado {
            get {
                return ResourceManager.GetString("LabelEncerrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inscrições Online.
        /// </summary>
        public static string LabelInscricoesOnline {
            get {
                return ResourceManager.GetString("LabelInscricoesOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identificação.
        /// </summary>
        public static string LabelNome {
            get {
                return ResourceManager.GetString("LabelNome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout Ficha Inscrição.
        /// </summary>
        public static string LabelTipoLayout {
            get {
                return ResourceManager.GetString("LabelTipoLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor Inscrição.
        /// </summary>
        public static string LabelValorInscricao {
            get {
                return ResourceManager.GetString("LabelValorInscricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opções.
        /// </summary>
        public static string LegendaCargos {
            get {
                return ResourceManager.GetString("LegendaCargos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dados do Concurso.
        /// </summary>
        public static string LegendaDadosConcurso {
            get {
                return ResourceManager.GetString("LegendaDadosConcurso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provas e Gabaritos.
        /// </summary>
        public static string LegendaProvasGabaritos {
            get {
                return ResourceManager.GetString("LegendaProvasGabaritos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publicações.
        /// </summary>
        public static string LegendaPublicacoes {
            get {
                return ResourceManager.GetString("LegendaPublicacoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;- Voltar.
        /// </summary>
        public static string LinkVoltar {
            get {
                return ResourceManager.GetString("LinkVoltar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adicionando arquivo....
        /// </summary>
        public static string MensagemAdicionandoAnexo {
            get {
                return ResourceManager.GetString("MensagemAdicionandoAnexo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adicionando opção....
        /// </summary>
        public static string MensagemAdicionandoCargo {
            get {
                return ResourceManager.GetString("MensagemAdicionandoCargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operação realizada com sucesso.
        /// </summary>
        public static string MensagemArquivoRemovidoSucesso {
            get {
                return ResourceManager.GetString("MensagemArquivoRemovidoSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operação realizada com sucesso.
        /// </summary>
        public static string MensagemCargoRemovidoSucesso {
            get {
                return ResourceManager.GetString("MensagemCargoRemovidoSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvando os dados do concurso....
        /// </summary>
        public static string MensagemSalvando {
            get {
                return ResourceManager.GetString("MensagemSalvando", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não.
        /// </summary>
        public static string OptionNao {
            get {
                return ResourceManager.GetString("OptionNao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sim.
        /// </summary>
        public static string OptionSim {
            get {
                return ResourceManager.GetString("OptionSim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro ao tentar salvar este concurso.
        /// </summary>
        public static string SalvarErro {
            get {
                return ResourceManager.GetString("SalvarErro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operação realizada com sucesso.
        /// </summary>
        public static string SalvarSucesso {
            get {
                return ResourceManager.GetString("SalvarSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publicações.
        /// </summary>
        public static string TableTitlePublicacoes {
            get {
                return ResourceManager.GetString("TableTitlePublicacoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concurso.
        /// </summary>
        public static string TituloTela {
            get {
                return ResourceManager.GetString("TituloTela", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O formato da data de vencimento do boleto está inválida.
        /// </summary>
        public static string ValidacaoDataBoletoFormatoInvalido {
            get {
                return ResourceManager.GetString("ValidacaoDataBoletoFormatoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data de vencimento do boleto é obrigatória.
        /// </summary>
        public static string ValidacaoDataBoletoObrigatorio {
            get {
                return ResourceManager.GetString("ValidacaoDataBoletoObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O formato da data de encerramento de exibição do botão de comprovante está inválida.
        /// </summary>
        public static string ValidacaoDataEncerramentoComprovanteFormatoInvalido {
            get {
                return ResourceManager.GetString("ValidacaoDataEncerramentoComprovanteFormatoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data de encerramento de exibição do botão de comprovante é obrigatória.
        /// </summary>
        public static string ValidacaoDataEncerramentoComprovanteObrigatorio {
            get {
                return ResourceManager.GetString("ValidacaoDataEncerramentoComprovanteObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O formato da data de encerramento de exibição da aba de isenção está inválida.
        /// </summary>
        public static string ValidacaoDataEncerramentoIsentoFormatoInvalido {
            get {
                return ResourceManager.GetString("ValidacaoDataEncerramentoIsentoFormatoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data de encerramento de exibição de exibição da aba de isenção é obrigatória.
        /// </summary>
        public static string ValidacaoDataEncerramentoIsentoObrigatorio {
            get {
                return ResourceManager.GetString("ValidacaoDataEncerramentoIsentoObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O formato da data de início de exibição do botão de classificação está inválida.
        /// </summary>
        public static string ValidacaoDataInicioClassificacaoFormatoInvalido {
            get {
                return ResourceManager.GetString("ValidacaoDataInicioClassificacaoFormatoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data de início de exibição do botão de classificação é obrigatória.
        /// </summary>
        public static string ValidacaoDataInicioClassificacaoObrigatorio {
            get {
                return ResourceManager.GetString("ValidacaoDataInicioClassificacaoObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O formato da data de início de exibição do botão de comprovante está inválida.
        /// </summary>
        public static string ValidacaoDataInicioComprovanteFormatoInvalido {
            get {
                return ResourceManager.GetString("ValidacaoDataInicioComprovanteFormatoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data de início de exibição do botão de comprovante é obrigatória.
        /// </summary>
        public static string ValidacaoDataInicioComprovanteObrigatorio {
            get {
                return ResourceManager.GetString("ValidacaoDataInicioComprovanteObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O formato da data de início de exibição de exibição da aba de isenção está inválida.
        /// </summary>
        public static string ValidacaoDataInicioIsentoFormatoInvalido {
            get {
                return ResourceManager.GetString("ValidacaoDataInicioIsentoFormatoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data de início de exibição de exibição da aba de isenção é obrigatória.
        /// </summary>
        public static string ValidacaoDataInicioIsentoObrigatorio {
            get {
                return ResourceManager.GetString("ValidacaoDataInicioIsentoObrigatorio", resourceCulture);
            }
        }
    }
}
