//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TGV.IPEFAE.Web.Resources.Admin.Concurso {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CSVColaboradores {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CSVColaboradores() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TGV.IPEFAE.Web.Resources.Admin.Concurso.CSVColaboradores", typeof(CSVColaboradores).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agencia.
        /// </summary>
        public static string Headeragencia {
            get {
                return ResourceManager.GetString("Headeragencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digito.
        /// </summary>
        public static string Headeragencia_digito {
            get {
                return ResourceManager.GetString("Headeragencia_digito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ativo.
        /// </summary>
        public static string Headerativo {
            get {
                return ResourceManager.GetString("Headerativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banco.
        /// </summary>
        public static string Headerbanco {
            get {
                return ResourceManager.GetString("Headerbanco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UF Carteira Trabalho.
        /// </summary>
        public static string Headercarteira_trabalho_estado {
            get {
                return ResourceManager.GetString("Headercarteira_trabalho_estado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nro Carteira Trabalho.
        /// </summary>
        public static string Headercarteira_trabalho_nro {
            get {
                return ResourceManager.GetString("Headercarteira_trabalho_nro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serie Carteira Trabalho.
        /// </summary>
        public static string Headercarteira_trabalho_serie {
            get {
                return ResourceManager.GetString("Headercarteira_trabalho_serie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código.
        /// </summary>
        public static string Headercodigo {
            get {
                return ResourceManager.GetString("Headercodigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conta Corrente.
        /// </summary>
        public static string Headerconta_corrente {
            get {
                return ResourceManager.GetString("Headerconta_corrente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digito.
        /// </summary>
        public static string Headerconta_corrente_digito {
            get {
                return ResourceManager.GetString("Headerconta_corrente_digito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPF.
        /// </summary>
        public static string Headercpf {
            get {
                return ResourceManager.GetString("Headercpf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dados OK.
        /// </summary>
        public static string Headerdados_ok {
            get {
                return ResourceManager.GetString("Headerdados_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string Headerdata_concurso {
            get {
                return ResourceManager.GetString("Headerdata_concurso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Nasc.
        /// </summary>
        public static string Headerdata_nascimento {
            get {
                return ResourceManager.GetString("Headerdata_nascimento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descontar INSS.
        /// </summary>
        public static string Headerdescontar_inss {
            get {
                return ResourceManager.GetString("Headerdescontar_inss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descontar ISS.
        /// </summary>
        public static string Headerdescontar_iss {
            get {
                return ResourceManager.GetString("Headerdescontar_iss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string Headeremail {
            get {
                return ResourceManager.GetString("Headeremail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bairro.
        /// </summary>
        public static string Headerendereco_bairro {
            get {
                return ResourceManager.GetString("Headerendereco_bairro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CEP.
        /// </summary>
        public static string Headerendereco_cep {
            get {
                return ResourceManager.GetString("Headerendereco_cep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cidade.
        /// </summary>
        public static string Headerendereco_cidade {
            get {
                return ResourceManager.GetString("Headerendereco_cidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complemento.
        /// </summary>
        public static string Headerendereco_complemento {
            get {
                return ResourceManager.GetString("Headerendereco_complemento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        public static string Headerendereco_estado {
            get {
                return ResourceManager.GetString("Headerendereco_estado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endereco.
        /// </summary>
        public static string Headerendereco_logradouro {
            get {
                return ResourceManager.GetString("Headerendereco_logradouro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nro.
        /// </summary>
        public static string Headerendereco_nro {
            get {
                return ResourceManager.GetString("Headerendereco_nro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado Civil.
        /// </summary>
        public static string Headerestado_civil {
            get {
                return ResourceManager.GetString("Headerestado_civil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funcao.
        /// </summary>
        public static string Headerfuncao_colaborador {
            get {
                return ResourceManager.GetString("Headerfuncao_colaborador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grau Instrucao.
        /// </summary>
        public static string Headergrau_instrucao {
            get {
                return ResourceManager.GetString("Headergrau_instrucao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Prova.
        /// </summary>
        public static string Headerlocal_concurso {
            get {
                return ResourceManager.GetString("Headerlocal_concurso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nacionalidade.
        /// </summary>
        public static string Headernacionalidade {
            get {
                return ResourceManager.GetString("Headernacionalidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cidade Naturalidade.
        /// </summary>
        public static string Headernaturalidade_cidade {
            get {
                return ResourceManager.GetString("Headernaturalidade_cidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado Naturalidade.
        /// </summary>
        public static string Headernaturalidade_estado {
            get {
                return ResourceManager.GetString("Headernaturalidade_estado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string Headernome {
            get {
                return ResourceManager.GetString("Headernome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concurso.
        /// </summary>
        public static string Headernome_concurso {
            get {
                return ResourceManager.GetString("Headernome_concurso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome Mae.
        /// </summary>
        public static string Headernome_mae {
            get {
                return ResourceManager.GetString("Headernome_mae", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome Pai.
        /// </summary>
        public static string Headernome_pai {
            get {
                return ResourceManager.GetString("Headernome_pai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIS PASEP NET.
        /// </summary>
        public static string Headerpis_pasep_net {
            get {
                return ResourceManager.GetString("Headerpis_pasep_net", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raca.
        /// </summary>
        public static string HeaderRaca {
            get {
                return ResourceManager.GetString("HeaderRaca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RG.
        /// </summary>
        public static string Headerrg {
            get {
                return ResourceManager.GetString("Headerrg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sexo.
        /// </summary>
        public static string Headersexo {
            get {
                return ResourceManager.GetString("Headersexo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefone 01.
        /// </summary>
        public static string Headertelefone_01 {
            get {
                return ResourceManager.GetString("Headertelefone_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefone 02.
        /// </summary>
        public static string Headertelefone_02 {
            get {
                return ResourceManager.GetString("Headertelefone_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo Conta.
        /// </summary>
        public static string Headertipo_conta {
            get {
                return ResourceManager.GetString("Headertipo_conta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nro Titulo Eleitor.
        /// </summary>
        public static string Headertitulo_eleitor_nro {
            get {
                return ResourceManager.GetString("Headertitulo_eleitor_nro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secao Titulo Eleitor.
        /// </summary>
        public static string Headertitulo_eleitor_secao {
            get {
                return ResourceManager.GetString("Headertitulo_eleitor_secao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zona Titulo Eleitor.
        /// </summary>
        public static string Headertitulo_eleitor_zona {
            get {
                return ResourceManager.GetString("Headertitulo_eleitor_zona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor Bruto.
        /// </summary>
        public static string Headervalor_bruto {
            get {
                return ResourceManager.GetString("Headervalor_bruto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor Liquido.
        /// </summary>
        public static string Headervalor_liquido {
            get {
                return ResourceManager.GetString("Headervalor_liquido", resourceCulture);
            }
        }
    }
}
