//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TGV.IPEFAE.Web.Resources.Admin.Concurso {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CSVInscritos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CSVInscritos() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TGV.IPEFAE.Web.Resources.Admin.Concurso.CSVInscritos", typeof(CSVInscritos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canhoto.
        /// </summary>
        public static string CSVCanhoto {
            get {
                return ResourceManager.GetString("CSVCanhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destro.
        /// </summary>
        public static string CSVDestro {
            get {
                return ResourceManager.GetString("CSVDestro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Isento.
        /// </summary>
        public static string CSVIsento {
            get {
                return ResourceManager.GetString("CSVIsento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não há nenhum inscrito neste concurso.
        /// </summary>
        public static string CSVNenhumInscrito {
            get {
                return ResourceManager.GetString("CSVNenhumInscrito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não.
        /// </summary>
        public static string CSVOutrasSolicitacoesVazio {
            get {
                return ResourceManager.GetString("CSVOutrasSolicitacoesVazio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não.
        /// </summary>
        public static string CSVSemDeficienciaVazio {
            get {
                return ResourceManager.GetString("CSVSemDeficienciaVazio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhum.
        /// </summary>
        public static string CSVSemTratamento {
            get {
                return ResourceManager.GetString("CSVSemTratamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não.
        /// </summary>
        public static string CSVTratEspecialNao {
            get {
                return ResourceManager.GetString("CSVTratEspecialNao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sim.
        /// </summary>
        public static string CSVTratEspecialSim {
            get {
                return ResourceManager.GetString("CSVTratEspecialSim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bairro.
        /// </summary>
        public static string HeaderBairro {
            get {
                return ResourceManager.GetString("HeaderBairro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opção.
        /// </summary>
        public static string HeaderCargoDescricao {
            get {
                return ResourceManager.GetString("HeaderCargoDescricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefone 02.
        /// </summary>
        public static string HeaderCelular {
            get {
                return ResourceManager.GetString("HeaderCelular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CEP.
        /// </summary>
        public static string HeaderCEP {
            get {
                return ResourceManager.GetString("HeaderCEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cidade.
        /// </summary>
        public static string HeaderCidade {
            get {
                return ResourceManager.GetString("HeaderCidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classificação.
        /// </summary>
        public static string HeaderClassificacao {
            get {
                return ResourceManager.GetString("HeaderClassificacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complemento.
        /// </summary>
        public static string HeaderComplemento {
            get {
                return ResourceManager.GetString("HeaderComplemento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concurso.
        /// </summary>
        public static string HeaderConcursoDescricao {
            get {
                return ResourceManager.GetString("HeaderConcursoDescricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPF.
        /// </summary>
        public static string HeaderCPF {
            get {
                return ResourceManager.GetString("HeaderCPF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curso do Aluno.
        /// </summary>
        public static string HeaderCursoIndicadoPor {
            get {
                return ResourceManager.GetString("HeaderCursoIndicadoPor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data da Inscrição.
        /// </summary>
        public static string HeaderData {
            get {
                return ResourceManager.GetString("HeaderData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Baixa.
        /// </summary>
        public static string HeaderDataBaixa {
            get {
                return ResourceManager.GetString("HeaderDataBaixa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Nascimento.
        /// </summary>
        public static string HeaderDataNascimento {
            get {
                return ResourceManager.GetString("HeaderDataNascimento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Prova.
        /// </summary>
        public static string HeaderDataProva {
            get {
                return ResourceManager.GetString("HeaderDataProva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deficiência.
        /// </summary>
        public static string HeaderDeficiencia {
            get {
                return ResourceManager.GetString("HeaderDeficiencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destro.
        /// </summary>
        public static string HeaderDestro {
            get {
                return ResourceManager.GetString("HeaderDestro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string HeaderEmail {
            get {
                return ResourceManager.GetString("HeaderEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endereço.
        /// </summary>
        public static string HeaderEndereco {
            get {
                return ResourceManager.GetString("HeaderEndereco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escolaridade Mãe.
        /// </summary>
        public static string HeaderEscolaridadeMae {
            get {
                return ResourceManager.GetString("HeaderEscolaridadeMae", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escolaridade Pai.
        /// </summary>
        public static string HeaderEscolaridadePai {
            get {
                return ResourceManager.GetString("HeaderEscolaridadePai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado Civil.
        /// </summary>
        public static string HeaderEstadoCivil {
            get {
                return ResourceManager.GetString("HeaderEstadoCivil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exerce Atividade Remunerada.
        /// </summary>
        public static string HeaderExerceAtividadeRemunerada {
            get {
                return ResourceManager.GetString("HeaderExerceAtividadeRemunerada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hora.
        /// </summary>
        public static string HeaderHora {
            get {
                return ResourceManager.GetString("HeaderHora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horario Prova.
        /// </summary>
        public static string HeaderHorarioProva {
            get {
                return ResourceManager.GetString("HeaderHorarioProva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local (Escola).
        /// </summary>
        public static string HeaderLocalEscolaProva {
            get {
                return ResourceManager.GetString("HeaderLocalEscolaProva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local da Prova.
        /// </summary>
        public static string HeaderLocalProva {
            get {
                return ResourceManager.GetString("HeaderLocalProva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motivo Optou pelo Curso.
        /// </summary>
        public static string HeaderMotivoOptouCurso {
            get {
                return ResourceManager.GetString("HeaderMotivoOptouCurso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motivo Optou UniFae.
        /// </summary>
        public static string HeaderMotivoOptouUniFae {
            get {
                return ResourceManager.GetString("HeaderMotivoOptouUniFae", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Necessita Tratamento Especial?.
        /// </summary>
        public static string HeaderNecessitaTratamento {
            get {
                return ResourceManager.GetString("HeaderNecessitaTratamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string HeaderNome {
            get {
                return ResourceManager.GetString("HeaderNome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicado pelo Aluno.
        /// </summary>
        public static string HeaderNomeIndicadoPor {
            get {
                return ResourceManager.GetString("HeaderNomeIndicadoPor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inscrição.
        /// </summary>
        public static string HeaderNumeroControle {
            get {
                return ResourceManager.GetString("HeaderNumeroControle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2ª Opção.
        /// </summary>
        public static string HeaderOpcao2 {
            get {
                return ResourceManager.GetString("HeaderOpcao2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3ª Opção.
        /// </summary>
        public static string HeaderOpcao3 {
            get {
                return ResourceManager.GetString("HeaderOpcao3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outras.
        /// </summary>
        public static string HeaderOutras {
            get {
                return ResourceManager.GetString("HeaderOutras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pontos CE.
        /// </summary>
        public static string HeaderPontosCE {
            get {
                return ResourceManager.GetString("HeaderPontosCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pontos CG.
        /// </summary>
        public static string HeaderPontosCG {
            get {
                return ResourceManager.GetString("HeaderPontosCG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pontos PP (Prova Pratica).
        /// </summary>
        public static string HeaderPontosPP {
            get {
                return ResourceManager.GetString("HeaderPontosPP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pontos TIT (Titulos).
        /// </summary>
        public static string HeaderPontosTIT {
            get {
                return ResourceManager.GetString("HeaderPontosTIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qtd. de filhos menores de 18.
        /// </summary>
        public static string HeaderQtdadeFilhos {
            get {
                return ResourceManager.GetString("HeaderQtdadeFilhos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renda Familiar Média.
        /// </summary>
        public static string HeaderRendaMensal {
            get {
                return ResourceManager.GetString("HeaderRendaMensal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RG.
        /// </summary>
        public static string HeaderRG {
            get {
                return ResourceManager.GetString("HeaderRG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado Emissor.
        /// </summary>
        public static string HeaderRGEstadoEmissor {
            get {
                return ResourceManager.GetString("HeaderRGEstadoEmissor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sala.
        /// </summary>
        public static string HeaderSalaProva {
            get {
                return ResourceManager.GetString("HeaderSalaProva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semestre do Aluno.
        /// </summary>
        public static string HeaderSemestreCursoIndicadoPor {
            get {
                return ResourceManager.GetString("HeaderSemestreCursoIndicadoPor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sexo.
        /// </summary>
        public static string HeaderSexo {
            get {
                return ResourceManager.GetString("HeaderSexo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Situação.
        /// </summary>
        public static string HeaderSituacao {
            get {
                return ResourceManager.GetString("HeaderSituacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefone 01.
        /// </summary>
        public static string HeaderTelefone {
            get {
                return ResourceManager.GetString("HeaderTelefone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo Ensino Fundamental.
        /// </summary>
        public static string HeaderTipoConcluiuEnsinoFundamental {
            get {
                return ResourceManager.GetString("HeaderTipoConcluiuEnsinoFundamental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo Ensino Médio.
        /// </summary>
        public static string HeaderTipoConcluiuEnsinoMedio {
            get {
                return ResourceManager.GetString("HeaderTipoConcluiuEnsinoMedio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ensino Médio Em.
        /// </summary>
        public static string HeaderTipoEnsinoMedio {
            get {
                return ResourceManager.GetString("HeaderTipoEnsinoMedio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Como Tomou Conhecimento UniFae.
        /// </summary>
        public static string HeaderTomouConhecimentoUniFae {
            get {
                return ResourceManager.GetString("HeaderTomouConhecimentoUniFae", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quais.
        /// </summary>
        public static string HeaderTomouConhecimentoUniFaeOutros {
            get {
                return ResourceManager.GetString("HeaderTomouConhecimentoUniFaeOutros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nota (Total dos pontos).
        /// </summary>
        public static string HeaderTotalPontos {
            get {
                return ResourceManager.GetString("HeaderTotalPontos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qual?.
        /// </summary>
        public static string HeaderTratamentoEspecialQual {
            get {
                return ResourceManager.GetString("HeaderTratamentoEspecialQual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UF.
        /// </summary>
        public static string HeaderUF {
            get {
                return ResourceManager.GetString("HeaderUF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor Inscrição.
        /// </summary>
        public static string HeaderValorInscricao {
            get {
                return ResourceManager.GetString("HeaderValorInscricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor Pago.
        /// </summary>
        public static string HeaderValorPago {
            get {
                return ResourceManager.GetString("HeaderValorPago", resourceCulture);
            }
        }
    }
}
