//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TGV.IPEFAE.Web.Resources.Admin.Concurso {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TGV.IPEFAE.Web.Resources.Admin.Concurso.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fechar.
        /// </summary>
        public static string BotaoFechar {
            get {
                return ResourceManager.GetString("BotaoFechar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string BotaoUpload {
            get {
                return ResourceManager.GetString("BotaoUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ativo.
        /// </summary>
        public static string ColunaAtivo {
            get {
                return ResourceManager.GetString("ColunaAtivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Opções.
        /// </summary>
        public static string ColunaCargos {
            get {
                return ResourceManager.GetString("ColunaCargos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concurso.
        /// </summary>
        public static string ColunaConcurso {
            get {
                return ResourceManager.GetString("ColunaConcurso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV.
        /// </summary>
        public static string ColunaCSV {
            get {
                return ResourceManager.GetString("ColunaCSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string ColunaData {
            get {
                return ResourceManager.GetString("ColunaData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Inscritos.
        /// </summary>
        public static string ColunaInscritos {
            get {
                return ResourceManager.GetString("ColunaInscritos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Pagos.
        /// </summary>
        public static string ColunaPagos {
            get {
                return ResourceManager.GetString("ColunaPagos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recursos.
        /// </summary>
        public static string ColunaRecursos {
            get {
                return ResourceManager.GetString("ColunaRecursos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Realize o upload do arquivo com dados do concurso.
        /// </summary>
        public static string LabelUploadArquivoConcurso {
            get {
                return ResourceManager.GetString("LabelUploadArquivoConcurso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Realize o upload do arquivo de remessa.
        /// </summary>
        public static string LabelUploadArquivoRemessa {
            get {
                return ResourceManager.GetString("LabelUploadArquivoRemessa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falha ao realizar upload.
        /// </summary>
        public static string LabelUploadErro {
            get {
                return ResourceManager.GetString("LabelUploadErro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload realizado com sucesso.
        /// </summary>
        public static string LabelUploadSucesso {
            get {
                return ResourceManager.GetString("LabelUploadSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + Adicionar concurso.
        /// </summary>
        public static string LinkAdicionarConcurso {
            get {
                return ResourceManager.GetString("LinkAdicionarConcurso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carregando lista concursos....
        /// </summary>
        public static string MensagemCarregando {
            get {
                return ResourceManager.GetString("MensagemCarregando", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gerando arquivo CSV de inscritos. Aguarde até o arquivo ser baixado....
        /// </summary>
        public static string MensagemDownloadCSV {
            get {
                return ResourceManager.GetString("MensagemDownloadCSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gerando arquivo de remessa. Aguarde até o arquivo ser baixado....
        /// </summary>
        public static string MensagemDownloadTXT {
            get {
                return ResourceManager.GetString("MensagemDownloadTXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processando arquivo de concurso....
        /// </summary>
        public static string MensagemProcessandoArquivoConcurso {
            get {
                return ResourceManager.GetString("MensagemProcessandoArquivoConcurso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processando arquivo de remessa....
        /// </summary>
        public static string MensagemProcessandoArquivoRemessa {
            get {
                return ResourceManager.GetString("MensagemProcessandoArquivoRemessa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhum concurso foi encontrado.
        /// </summary>
        public static string NenhumConcursoEncontrado {
            get {
                return ResourceManager.GetString("NenhumConcursoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista de concursos cadastrados no sistema.
        /// </summary>
        public static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adicionar Empresa.
        /// </summary>
        public static string TitleAdicionarEmpresa {
            get {
                return ResourceManager.GetString("TitleAdicionarEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download CSV inscritos.
        /// </summary>
        public static string TitleCSV {
            get {
                return ResourceManager.GetString("TitleCSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download arquivo remessa.
        /// </summary>
        public static string TitleDownloadRemessa {
            get {
                return ResourceManager.GetString("TitleDownloadRemessa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar concurso.
        /// </summary>
        public static string TitleEditar {
            get {
                return ResourceManager.GetString("TitleEditar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gerenciar inscritos.
        /// </summary>
        public static string TitleGerenciarInscritos {
            get {
                return ResourceManager.GetString("TitleGerenciarInscritos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualizar recursos.
        /// </summary>
        public static string TitleRecursos {
            get {
                return ResourceManager.GetString("TitleRecursos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Arquivo de Remessa.
        /// </summary>
        public static string TitleRemessa {
            get {
                return ResourceManager.GetString("TitleRemessa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Dados Concurso.
        /// </summary>
        public static string TitleUpdateConcurso {
            get {
                return ResourceManager.GetString("TitleUpdateConcurso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gerenciar Concursos Existentes.
        /// </summary>
        public static string TituloTela {
            get {
                return ResourceManager.GetString("TituloTela", resourceCulture);
            }
        }
    }
}
