//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TGV.IPEFAE.Web.Resources.Recurso {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class _RecursoIsencao {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _RecursoIsencao() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TGV.IPEFAE.Web.Resources.Recurso._RecursoIsencao", typeof(_RecursoIsencao).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPF.
        /// </summary>
        public static string LabelCPF {
            get {
                return ResourceManager.GetString("LabelCPF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Expedição.
        /// </summary>
        public static string LabelDataExpedicaoRG {
            get {
                return ResourceManager.GetString("LabelDataExpedicaoRG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Nascimento.
        /// </summary>
        public static string LabelDataNascimento {
            get {
                return ResourceManager.GetString("LabelDataNascimento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venho requerer a isenção de pagamento do valor da inscrição neste certame..
        /// </summary>
        public static string LabelDeclaracaoP01 {
            get {
                return ResourceManager.GetString("LabelDeclaracaoP01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declaro estar inscrito no Cadastro Único, que sou membro de família de baixa renda e que todas as informações prestadas são verídicas, sou responsável por todos os dados fornecidos a fim de que a consulta ao Ministério do Desenvolvimento Social e Combate a Fome - MDS seja feita..
        /// </summary>
        public static string LabelDeclaracaoP02 {
            get {
                return ResourceManager.GetString("LabelDeclaracaoP02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DECLARAÇÃO.
        /// </summary>
        public static string LabelDeclaracaoTitulo {
            get {
                return ResourceManager.GetString("LabelDeclaracaoTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identificação Social.
        /// </summary>
        public static string LabelIdentificacaoSocial {
            get {
                return ResourceManager.GetString("LabelIdentificacaoSocial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NIS (Atribuido pelo cadiúnico).
        /// </summary>
        public static string LabelIdentificacaoSocial_Sub {
            get {
                return ResourceManager.GetString("LabelIdentificacaoSocial_Sub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string LabelNomeCompleto {
            get {
                return ResourceManager.GetString("LabelNomeCompleto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome Completo Mãe.
        /// </summary>
        public static string LabelNomeMae {
            get {
                return ResourceManager.GetString("LabelNomeMae", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Órgão Expedidor.
        /// </summary>
        public static string LabelOrgaoExpedidorRG {
            get {
                return ResourceManager.GetString("LabelOrgaoExpedidorRG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doc. Identidade.
        /// </summary>
        public static string LabelRG {
            get {
                return ResourceManager.GetString("LabelRG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sexo.
        /// </summary>
        public static string LabelSexo {
            get {
                return ResourceManager.GetString("LabelSexo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitação de Isenção.
        /// </summary>
        public static string LegendSolicitacaoIsencao {
            get {
                return ResourceManager.GetString("LegendSolicitacaoIsencao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feminino.
        /// </summary>
        public static string OptionFeminino {
            get {
                return ResourceManager.GetString("OptionFeminino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Masculino.
        /// </summary>
        public static string OptionMasculino {
            get {
                return ResourceManager.GetString("OptionMasculino", resourceCulture);
            }
        }
    }
}
