//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TGV.IPEFAE.Web.Resources.Recurso {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class _Recurso {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _Recurso() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TGV.IPEFAE.Web.Resources.Recurso._Recurso", typeof(_Recurso).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastrar Recurso.
        /// </summary>
        public static string BotaoCadastrarRecurso {
            get {
                return ResourceManager.GetString("BotaoCadastrarRecurso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviar.
        /// </summary>
        public static string BotaoEnviar {
            get {
                return ResourceManager.GetString("BotaoEnviar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string BotaoOK {
            get {
                return ResourceManager.GetString("BotaoOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arquivo Anexo.
        /// </summary>
        public static string LabelAnexosRequerente {
            get {
                return ResourceManager.GetString("LabelAnexosRequerente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargo:.
        /// </summary>
        public static string LabelCargo {
            get {
                return ResourceManager.GetString("LabelCargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concurso.
        /// </summary>
        public static string LabelConcurso {
            get {
                return ResourceManager.GetString("LabelConcurso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPF NÃO CADASTRADO PARA ESTE CONCURSO.
        /// </summary>
        public static string LabelCPFNaoEncontrado {
            get {
                return ResourceManager.GetString("LabelCPFNaoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digite seu CPF para enviar um recurso.
        /// </summary>
        public static string LabelDigiteCPF {
            get {
                return ResourceManager.GetString("LabelDigiteCPF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inscrição:.
        /// </summary>
        public static string LabelInscricao {
            get {
                return ResourceManager.GetString("LabelInscricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mensagem.
        /// </summary>
        public static string LabelMensagem {
            get {
                return ResourceManager.GetString("LabelMensagem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para impetrar recurso digite sua fundamentação no campo &quot;mensagem&quot; e clique em &quot;enviar&quot;ou faça o upload em seu computador do arquivo com a fundamentação e clique em &quot;enviar&quot;.
        /// </summary>
        public static string LabelMensagemAviso {
            get {
                return ResourceManager.GetString("LabelMensagemAviso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Os recursos serão analisados e julgados de acordo com as disposições contidas no edital.
        /// </summary>
        public static string LabelMensagemAvisoJulgamento {
            get {
                return ResourceManager.GetString("LabelMensagemAvisoJulgamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome:.
        /// </summary>
        public static string LabelRequerente {
            get {
                return ResourceManager.GetString("LabelRequerente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Somente arquivos PDF, DOC ou DOCX e com tamanho máximo de 2MB).
        /// </summary>
        public static string LabelSomentePDF {
            get {
                return ResourceManager.GetString("LabelSomentePDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Somente arquivos PDF, DOC ou DOCX e com tamanho máximo de 2MB.
        /// </summary>
        public static string LabelUploadErro {
            get {
                return ResourceManager.GetString("LabelUploadErro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload realizado com sucesso!.
        /// </summary>
        public static string LabelUploadSucesso {
            get {
                return ResourceManager.GetString("LabelUploadSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carregando Anexos....
        /// </summary>
        public static string MensagemCarregandoAnexos {
            get {
                return ResourceManager.GetString("MensagemCarregandoAnexos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anexando arquivos e enviando resposta ao requerente....
        /// </summary>
        public static string MensagemEnviando {
            get {
                return ResourceManager.GetString("MensagemEnviando", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abrindo recurso....
        /// </summary>
        public static string MensagemEnviandoRecurso {
            get {
                return ResourceManager.GetString("MensagemEnviandoRecurso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Realizando upload do arquivo....
        /// </summary>
        public static string MensagemRealizandoUpload {
            get {
                return ResourceManager.GetString("MensagemRealizandoUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione uma matrícula.
        /// </summary>
        public static string MensagemSelecioneUmaMatricula {
            get {
                return ResourceManager.GetString("MensagemSelecioneUmaMatricula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resposta ao recurso enviada com sucesso.
        /// </summary>
        public static string MensagemSucesso {
            get {
                return ResourceManager.GetString("MensagemSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recurso nº {0} impetrado com sucesso.
        /// </summary>
        public static string RecursoAbertoSucesso {
            get {
                return ResourceManager.GetString("RecursoAbertoSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pesquisar por CPF.
        /// </summary>
        public static string TitlePesquisar {
            get {
                return ResourceManager.GetString("TitlePesquisar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Somente arquivos PDF, DOC ou DOCX e com tamanho máximo de 2MB.
        /// </summary>
        public static string ValidacaoArquivoFormatoInvalido {
            get {
                return ResourceManager.GetString("ValidacaoArquivoFormatoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O CPF é obrigatório.
        /// </summary>
        public static string ValidacaoCPFObrigatorio {
            get {
                return ResourceManager.GetString("ValidacaoCPFObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O formato da data de nascimento está inválido.
        /// </summary>
        public static string ValidacaoDataNascFormatoInvalido {
            get {
                return ResourceManager.GetString("ValidacaoDataNascFormatoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data de nascimento é obrigatória.
        /// </summary>
        public static string ValidacaoDataNascObrigatorio {
            get {
                return ResourceManager.GetString("ValidacaoDataNascObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O formato da data de expedição está inválido.
        /// </summary>
        public static string ValidacaoDataRGFormatoInvalido {
            get {
                return ResourceManager.GetString("ValidacaoDataRGFormatoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data de expedição do RG é obrigatória.
        /// </summary>
        public static string ValidacaoDataRGObrigatorio {
            get {
                return ResourceManager.GetString("ValidacaoDataRGObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A identificação social é obrigatória.
        /// </summary>
        public static string ValidacaoIdentSocialObrigatorio {
            get {
                return ResourceManager.GetString("ValidacaoIdentSocialObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A mensagem é obrigatória.
        /// </summary>
        public static string ValidacaoMensagemObrigatoria {
            get {
                return ResourceManager.GetString("ValidacaoMensagemObrigatoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome completo da mãe é obrigatório.
        /// </summary>
        public static string ValidacaoNomeMaeObrigatorio {
            get {
                return ResourceManager.GetString("ValidacaoNomeMaeObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome completo é obrigatório.
        /// </summary>
        public static string ValidacaoNomeObrigatorio {
            get {
                return ResourceManager.GetString("ValidacaoNomeObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O órgão expedidor é obrigatório.
        /// </summary>
        public static string ValidacaoOrgaoExpedidorObrigatorio {
            get {
                return ResourceManager.GetString("ValidacaoOrgaoExpedidorObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O documento de identidade é obrigatório.
        /// </summary>
        public static string ValidacaoRGObrigatorio {
            get {
                return ResourceManager.GetString("ValidacaoRGObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O sexo é obrigatório.
        /// </summary>
        public static string ValidacaoSexoObrigatorio {
            get {
                return ResourceManager.GetString("ValidacaoSexoObrigatorio", resourceCulture);
            }
        }
    }
}
