//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TGV.IPEFAE.Web.Resources.Home {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TGV.IPEFAE.Web.Resources.Home.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concursos.
        /// </summary>
        public static string ItemConcursos {
            get {
                return ResourceManager.GetString("ItemConcursos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estágio.
        /// </summary>
        public static string ItemEstagios {
            get {
                return ResourceManager.GetString("ItemEstagios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outros Serviços.
        /// </summary>
        public static string ItemOutrosServicos {
            get {
                return ResourceManager.GetString("ItemOutrosServicos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processos Seletivos.
        /// </summary>
        public static string ItemProcessoSeletivo {
            get {
                return ResourceManager.GetString("ItemProcessoSeletivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vestibulares.
        /// </summary>
        public static string ItemVestibulares {
            get {
                return ResourceManager.GetString("ItemVestibulares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vestibular UniFAE 2018.
        /// </summary>
        public static string ItemVestibularUniFae {
            get {
                return ResourceManager.GetString("ItemVestibularUniFae", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serviços.
        /// </summary>
        public static string ServicesH2Servicos {
            get {
                return ResourceManager.GetString("ServicesH2Servicos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O INSTITUTO DE PESQUISAS ECONÔMICAS – IPEFAE (CNPJ: 00.582.074/0001-83) atende ao inciso XIII, do artigo 24, da Lei Federal nº 8666/93, depois alterada pela Lei 8.883/94, que dispõe sobre a contratação por dispensa de licitação:.
        /// </summary>
        public static string ServicesH3Principal {
            get {
                return ResourceManager.GetString("ServicesH3Principal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constituído como pessoa jurídica, de natureza privada, sem fins lucrativos, tem por objetivo desenvolver projetos na área de educação, elaborando, disseminando e executando diversos programas e serviços..
        /// </summary>
        public static string ServicesH3Terciario {
            get {
                return ResourceManager.GetString("ServicesH3Terciario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concursos Públicos.
        /// </summary>
        public static string ServicesH4ConcursoPublico {
            get {
                return ResourceManager.GetString("ServicesH4ConcursoPublico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultoria.
        /// </summary>
        public static string ServicesH4Consultoria {
            get {
                return ResourceManager.GetString("ServicesH4Consultoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estágio.
        /// </summary>
        public static string ServicesH4Estagio {
            get {
                return ResourceManager.GetString("ServicesH4Estagio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palestras.
        /// </summary>
        public static string ServicesH4Palestras {
            get {
                return ResourceManager.GetString("ServicesH4Palestras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to “...Instituição brasileira incumbida regimental ou  estatutariamente de pesquisa, do ensino ou do desenvolvimento institucional ou de instituição dedicada à recuperação social do preso, desde que a contratada detenha inquestionável reputação ético profissional e não tenha fins lucrativos”..
        /// </summary>
        public static string ServicesH4Secundario {
            get {
                return ResourceManager.GetString("ServicesH4Secundario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projetos Sócio-Educativos.
        /// </summary>
        public static string ServicesH4SocioEducativo {
            get {
                return ResourceManager.GetString("ServicesH4SocioEducativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treinamentos.
        /// </summary>
        public static string ServicesH4Treinamentos {
            get {
                return ResourceManager.GetString("ServicesH4Treinamentos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A realização de Concursos Públicos, Processos Seletivos e certames em geral, requer um planejamento sintonizado com as necessidades de cada cliente e ações de execução centralizadas na performance de resultados, além de uma grande responsabilidade, envolvendo o desenvolvimento integrado de uma complexa logística. O IPEFAE mantém rígido controle e sigilo desde o primeiro contato do cliente, assessorando com segurança todas as etapas do trabalho..
        /// </summary>
        public static string ServicesPConcursoPublico {
            get {
                return ResourceManager.GetString("ServicesPConcursoPublico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De forma simples e prática, o IPEFAE atua na busca de soluções que possam ser efetivamente traduzidas em inovação, desenvolvimento, qualidade e melhoria nos resultados, respeitando a identidade e a filosofia de cada organização. A expressiva capacitação, experiência, vivência profissional e formação multidisciplinar dos consultores, amparam o desenvolvimento e suporte técnico dos projetos..
        /// </summary>
        public static string ServicesPConsultoria {
            get {
                return ResourceManager.GetString("ServicesPConsultoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O estágio é fundamental para que o futuro profissional inicie, na prática do dia a dia, a aplicação do conhecimento acadêmico adquirido. É o começo de uma preparação. É o primeiro passo para o sucesso. Atento a isto o IPEFAE atua com o Programa de Estágio, oportunizando a qualificação e o desenvolvimento de novos profissionais, inserindo-os no mercado de trabalho e concedendo diversas vantagens às empresas..
        /// </summary>
        public static string ServicesPEstagio {
            get {
                return ResourceManager.GetString("ServicesPEstagio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Através das palestras é possível lapidar e recriar talentos, ampliando o olhar crítico e motivando pessoas. As palestras permitem aos profissionais ampliarem sua performance e otimizarem seu rendimento..
        /// </summary>
        public static string ServicesPPalestras {
            get {
                return ResourceManager.GetString("ServicesPPalestras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ética, trabalho, inovação, criatividade e o bom uso dos recursos são lemas perseguidos pelo IPEFAE na prestação de serviços. Possuidor de equipe de profissionais habilitados nas áreas de artes, comunicação, dança, informática, gestão, música, matemática, nutrição, psicologia, entre muitos outros, agregou várias experiências de sucesso no setor educacional, com a intervenção direta de suporte na gestão e nos variados ambientes educativos..
        /// </summary>
        public static string ServicesPSocioEducativo {
            get {
                return ResourceManager.GetString("ServicesPSocioEducativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O IPEFAE é especializado em treinamentos, palestras e eventos para organizações que buscam diferenciais para melhor enfrentar os desafios do mercado. Os instrutores e consultores aliam suas qualificações e experiências garantindo resultados superiores aos profissionais treinados..
        /// </summary>
        public static string ServicesPTreinamentos {
            get {
                return ResourceManager.GetString("ServicesPTreinamentos", resourceCulture);
            }
        }
    }
}
