//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TGV.IPEFAE.Web.Resources.Admin.Recurso {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Cadastro {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Cadastro() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TGV.IPEFAE.Web.Resources.Admin.Recurso.Cadastro", typeof(Cadastro).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviar.
        /// </summary>
        public static string BotaoEnviar {
            get {
                return ResourceManager.GetString("BotaoEnviar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voltar.
        /// </summary>
        public static string BotaoVoltar {
            get {
                return ResourceManager.GetString("BotaoVoltar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O comentário é obrigatório.
        /// </summary>
        public static string ComentarioObrigatorio {
            get {
                return ResourceManager.GetString("ComentarioObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anexos Atendente.
        /// </summary>
        public static string LabelAnexosAtendente {
            get {
                return ResourceManager.GetString("LabelAnexosAtendente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anexos Requerente.
        /// </summary>
        public static string LabelAnexosRequerente {
            get {
                return ResourceManager.GetString("LabelAnexosRequerente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comentário.
        /// </summary>
        public static string LabelComentario {
            get {
                return ResourceManager.GetString("LabelComentario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concurso.
        /// </summary>
        public static string LabelConcurso {
            get {
                return ResourceManager.GetString("LabelConcurso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Abertura Recurso.
        /// </summary>
        public static string LabelDataAbertura {
            get {
                return ResourceManager.GetString("LabelDataAbertura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mensagem.
        /// </summary>
        public static string LabelMensagem {
            get {
                return ResourceManager.GetString("LabelMensagem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargo.
        /// </summary>
        public static string LabelNomeCargo {
            get {
                return ResourceManager.GetString("LabelNomeCargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requerente (Matrícula).
        /// </summary>
        public static string LabelRequerente {
            get {
                return ResourceManager.GetString("LabelRequerente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Somente arquivos PDF, DOC ou DOCX e com tamanho máximo de 2MB).
        /// </summary>
        public static string LabelSomentePDF {
            get {
                return ResourceManager.GetString("LabelSomentePDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Somente arquivos PDF, DOC ou DOCX e com tamanho máximo de 2MB.
        /// </summary>
        public static string LabelUploadErro {
            get {
                return ResourceManager.GetString("LabelUploadErro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload realizado com sucesso!.
        /// </summary>
        public static string LabelUploadSucesso {
            get {
                return ResourceManager.GetString("LabelUploadSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carregando Anexos....
        /// </summary>
        public static string MensagemCarregandoAnexos {
            get {
                return ResourceManager.GetString("MensagemCarregandoAnexos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anexando arquivos e enviando resposta ao requerente....
        /// </summary>
        public static string MensagemEnviando {
            get {
                return ResourceManager.GetString("MensagemEnviando", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Realizando upload do arquivo....
        /// </summary>
        public static string MensagemRealizandoUpload {
            get {
                return ResourceManager.GetString("MensagemRealizandoUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resposta ao recurso enviada com sucesso.
        /// </summary>
        public static string MensagemSucesso {
            get {
                return ResourceManager.GetString("MensagemSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A opção Deferido ou Indeferido é obrigatória.
        /// </summary>
        public static string RespostaObrigatorio {
            get {
                return ResourceManager.GetString("RespostaObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recurso #{0} - {1}.
        /// </summary>
        public static string TituloTela {
            get {
                return ResourceManager.GetString("TituloTela", resourceCulture);
            }
        }
    }
}
