//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TGV.IPEFAE.Web.Resources.Admin.Recurso {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TGV.IPEFAE.Web.Resources.Admin.Recurso.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atendente.
        /// </summary>
        public static string ColunaAtendente {
            get {
                return ResourceManager.GetString("ColunaAtendente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ativo.
        /// </summary>
        public static string ColunaAtivo {
            get {
                return ResourceManager.GetString("ColunaAtivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abertura.
        /// </summary>
        public static string ColunaDataAbertura {
            get {
                return ResourceManager.GetString("ColunaDataAbertura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Respondido Em.
        /// </summary>
        public static string ColunaDataAtendimento {
            get {
                return ResourceManager.GetString("ColunaDataAtendimento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Candidato.
        /// </summary>
        public static string ColunaNome {
            get {
                return ResourceManager.GetString("ColunaNome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protocolo.
        /// </summary>
        public static string ColunaProtocolo {
            get {
                return ResourceManager.GetString("ColunaProtocolo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string ColunaStatus {
            get {
                return ResourceManager.GetString("ColunaStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;- Voltar.
        /// </summary>
        public static string LinkVoltar {
            get {
                return ResourceManager.GetString("LinkVoltar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carregando lista recursos....
        /// </summary>
        public static string MensagemCarregando {
            get {
                return ResourceManager.GetString("MensagemCarregando", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhum recurso foi encontrado.
        /// </summary>
        public static string NenhumRecursoEncontrado {
            get {
                return ResourceManager.GetString("NenhumRecursoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deferido.
        /// </summary>
        public static string StatusAprovado {
            get {
                return ResourceManager.GetString("StatusAprovado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo.
        /// </summary>
        public static string StatusNovo {
            get {
                return ResourceManager.GetString("StatusNovo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indeferido.
        /// </summary>
        public static string StatusReprovado {
            get {
                return ResourceManager.GetString("StatusReprovado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista de recursos cadastrados no sistema.
        /// </summary>
        public static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responder recurso.
        /// </summary>
        public static string TitleResponder {
            get {
                return ResourceManager.GetString("TitleResponder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualizar dados recurso.
        /// </summary>
        public static string TitleVisualizar {
            get {
                return ResourceManager.GetString("TitleVisualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recursos.
        /// </summary>
        public static string TituloTela {
            get {
                return ResourceManager.GetString("TituloTela", resourceCulture);
            }
        }
    }
}
