//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TGV.IPEFAE.Web.Resources.Estagio {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TGV.IPEFAE.Web.Resources.Estagio.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        public static string BotaoCancelar {
            get {
                return ResourceManager.GetString("BotaoCancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continuar.
        /// </summary>
        public static string BotaoContinuar {
            get {
                return ResourceManager.GetString("BotaoContinuar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criar Cadastro.
        /// </summary>
        public static string BotaoCriarCadastro {
            get {
                return ResourceManager.GetString("BotaoCriarCadastro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recuperar Senha.
        /// </summary>
        public static string BotaoEnviarEmail {
            get {
                return ResourceManager.GetString("BotaoEnviarEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail ou senha não encontrado.
        /// </summary>
        public static string ErroLogin {
            get {
                return ResourceManager.GetString("ErroLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPF não encontrado.
        /// </summary>
        public static string LabelCPFNaoEncontrado {
            get {
                return ResourceManager.GetString("LabelCPFNaoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digite seu CPF para receber sua senha.
        /// </summary>
        public static string LabelDigiteCPF {
            get {
                return ResourceManager.GetString("LabelDigiteCPF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string LabelEmail {
            get {
                return ResourceManager.GetString("LabelEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esqueci minha senha.
        /// </summary>
        public static string LabelEsqueciSenha {
            get {
                return ResourceManager.GetString("LabelEsqueciSenha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já tenho cadastro.
        /// </summary>
        public static string LabelJaTenhoCadastro {
            get {
                return ResourceManager.GetString("LabelJaTenhoCadastro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não tenho cadastro.
        /// </summary>
        public static string LabelNaoTenhoCadastro {
            get {
                return ResourceManager.GetString("LabelNaoTenhoCadastro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha.
        /// </summary>
        public static string LabelSenha {
            get {
                return ResourceManager.GetString("LabelSenha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crie aqui seu currículo.
        /// </summary>
        public static string Li1Linha {
            get {
                return ResourceManager.GetString("Li1Linha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receba oportunidades de estágio.
        /// </summary>
        public static string Li2Linha {
            get {
                return ResourceManager.GetString("Li2Linha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salve seus dados para imprimir seu cv sempre que quiser.
        /// </summary>
        public static string Li3Linha {
            get {
                return ResourceManager.GetString("Li3Linha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Realizando o login ....
        /// </summary>
        public static string MensagemBlockUILogin {
            get {
                return ResourceManager.GetString("MensagemBlockUILogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Realizando o logoff ....
        /// </summary>
        public static string MensagemBlockUILogoff {
            get {
                return ResourceManager.GetString("MensagemBlockUILogoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail enviado com sucesso.
        /// </summary>
        public static string MensagemEmailEnviadoSucesso {
            get {
                return ResourceManager.GetString("MensagemEmailEnviadoSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reenviando senha ....
        /// </summary>
        public static string MensagemReenviandoSenha {
            get {
                return ResourceManager.GetString("MensagemReenviandoSenha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O CPF é obrigatório.
        /// </summary>
        public static string ObrigatorioCPF {
            get {
                return ResourceManager.GetString("ObrigatorioCPF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O e-mail é obrigatório.
        /// </summary>
        public static string ObrigatorioEmail {
            get {
                return ResourceManager.GetString("ObrigatorioEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formato do e-mail inválido.
        /// </summary>
        public static string ObrigatorioFormatoEmail {
            get {
                return ResourceManager.GetString("ObrigatorioFormatoEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha é obrigatória.
        /// </summary>
        public static string ObrigatorioSenha {
            get {
                return ResourceManager.GetString("ObrigatorioSenha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to digite seu e-mail.
        /// </summary>
        public static string PlaceHolderEmail {
            get {
                return ResourceManager.GetString("PlaceHolderEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identificação - Estágio.
        /// </summary>
        public static string TituloTela {
            get {
                return ResourceManager.GetString("TituloTela", resourceCulture);
            }
        }
    }
}
