//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TGV.IPEFAE.Web.Resources.Estagio {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Preview {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Preview() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TGV.IPEFAE.Web.Resources.Estagio.Preview", typeof(Preview).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atividades Desenvolvidas.
        /// </summary>
        public static string LabelAtividadesDesenvolvidas {
            get {
                return ResourceManager.GetString("LabelAtividadesDesenvolvidas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargo:.
        /// </summary>
        public static string LabelCargo {
            get {
                return ResourceManager.GetString("LabelCargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail:.
        /// </summary>
        public static string LabelEmail {
            get {
                return ResourceManager.GetString("LabelEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to até.
        /// </summary>
        public static string LabelExperienciaTerminoAte {
            get {
                return ResourceManager.GetString("LabelExperienciaTerminoAte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to anos.
        /// </summary>
        public static string LabelIdadeAnos {
            get {
                return ResourceManager.GetString("LabelIdadeAnos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Início.
        /// </summary>
        public static string LabelInicio {
            get {
                return ResourceManager.GetString("LabelInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefone:.
        /// </summary>
        public static string LabelTelefone {
            get {
                return ResourceManager.GetString("LabelTelefone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Término.
        /// </summary>
        public static string LabelTermino {
            get {
                return ResourceManager.GetString("LabelTermino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ano.
        /// </summary>
        public static string LabelTipoAno {
            get {
                return ResourceManager.GetString("LabelTipoAno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semestre.
        /// </summary>
        public static string LabelTipoSemestre {
            get {
                return ResourceManager.GetString("LabelTipoSemestre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cursos e Capacitações.
        /// </summary>
        public static string LabelTituloCursos {
            get {
                return ResourceManager.GetString("LabelTituloCursos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experiência Profissional.
        /// </summary>
        public static string LabelTituloExperiencia {
            get {
                return ResourceManager.GetString("LabelTituloExperiencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formação.
        /// </summary>
        public static string LabelTituloFormacao {
            get {
                return ResourceManager.GetString("LabelTituloFormacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informações Adicionais.
        /// </summary>
        public static string LabelTituloInfoAdicionais {
            get {
                return ResourceManager.GetString("LabelTituloInfoAdicionais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objetivo.
        /// </summary>
        public static string LabelTituloObjetivo {
            get {
                return ResourceManager.GetString("LabelTituloObjetivo", resourceCulture);
            }
        }
    }
}
