//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TGV.IPEFAE.Web.Resources.Admin.Usuario {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Cadastro {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Cadastro() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TGV.IPEFAE.Web.Resources.Admin.Usuario.Cadastro", typeof(Cadastro).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvar.
        /// </summary>
        public static string BotaoSalvar {
            get {
                return ResourceManager.GetString("BotaoSalvar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A confirmação da senha é obrigatória.
        /// </summary>
        public static string ConfirmacaoSenhaObrigatorio {
            get {
                return ResourceManager.GetString("ConfirmacaoSenhaObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O e-mail é obrigatório.
        /// </summary>
        public static string EmailObrigatorio {
            get {
                return ResourceManager.GetString("EmailObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O formato do e-mail está inválido.
        /// </summary>
        public static string FormatoInvalidoEmail {
            get {
                return ResourceManager.GetString("FormatoInvalidoEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ativo.
        /// </summary>
        public static string LabelAtivo {
            get {
                return ResourceManager.GetString("LabelAtivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmação Senha.
        /// </summary>
        public static string LabelConfirmacaoSenha {
            get {
                return ResourceManager.GetString("LabelConfirmacaoSenha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string LabelEmail {
            get {
                return ResourceManager.GetString("LabelEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string LabelNome {
            get {
                return ResourceManager.GetString("LabelNome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissão.
        /// </summary>
        public static string LabelPermissao {
            get {
                return ResourceManager.GetString("LabelPermissao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concursos.
        /// </summary>
        public static string LabelPermissaoAdminConcursos {
            get {
                return ResourceManager.GetString("LabelPermissaoAdminConcursos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estágios.
        /// </summary>
        public static string LabelPermissaoAdminEstagios {
            get {
                return ResourceManager.GetString("LabelPermissaoAdminEstagios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrador Geral.
        /// </summary>
        public static string LabelPermissaoAdminGeral {
            get {
                return ResourceManager.GetString("LabelPermissaoAdminGeral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vestibulares.
        /// </summary>
        public static string LabelPermissaoAdminVestibulares {
            get {
                return ResourceManager.GetString("LabelPermissaoAdminVestibulares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha.
        /// </summary>
        public static string LabelSenha {
            get {
                return ResourceManager.GetString("LabelSenha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Situação.
        /// </summary>
        public static string LabelSituacao {
            get {
                return ResourceManager.GetString("LabelSituacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefone.
        /// </summary>
        public static string LabelTelefone {
            get {
                return ResourceManager.GetString("LabelTelefone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clique aqui para trocar a sua senha.
        /// </summary>
        public static string LabelTrocarSenha {
            get {
                return ResourceManager.GetString("LabelTrocarSenha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvando dados do usuário....
        /// </summary>
        public static string MensagemSalvando {
            get {
                return ResourceManager.GetString("MensagemSalvando", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome é obrigatório.
        /// </summary>
        public static string NomeObrigatorio {
            get {
                return ResourceManager.GetString("NomeObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome do usuário.
        /// </summary>
        public static string PlaceHolderNome {
            get {
                return ResourceManager.GetString("PlaceHolderNome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de telefone.
        /// </summary>
        public static string PlaceHolderTelefone {
            get {
                return ResourceManager.GetString("PlaceHolderTelefone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro ao salvar os dados do usuário.
        /// </summary>
        public static string SalvarErro {
            get {
                return ResourceManager.GetString("SalvarErro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operação realizada com sucesso.
        /// </summary>
        public static string SalvarSucesso {
            get {
                return ResourceManager.GetString("SalvarSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha e sua confirmação devem ser iguais.
        /// </summary>
        public static string SenhaConfirmacaoIguais {
            get {
                return ResourceManager.GetString("SenhaConfirmacaoIguais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha é obrigatória.
        /// </summary>
        public static string SenhaObrigatorio {
            get {
                return ResourceManager.GetString("SenhaObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O telefone é obrigatório.
        /// </summary>
        public static string TelefoneObrigatorio {
            get {
                return ResourceManager.GetString("TelefoneObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastro Usuário.
        /// </summary>
        public static string TituloTela {
            get {
                return ResourceManager.GetString("TituloTela", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voltar a lista.
        /// </summary>
        public static string VoltarLista {
            get {
                return ResourceManager.GetString("VoltarLista", resourceCulture);
            }
        }
    }
}
