//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TGV.IPEFAE.Web.Resources.Admin.Usuario {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TGV.IPEFAE.Web.Resources.Admin.Usuario.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ativo.
        /// </summary>
        public static string ColunaAtivo {
            get {
                return ResourceManager.GetString("ColunaAtivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string ColunaEmail {
            get {
                return ResourceManager.GetString("ColunaEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string ColunaNome {
            get {
                return ResourceManager.GetString("ColunaNome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissão.
        /// </summary>
        public static string ColunaPermissao {
            get {
                return ResourceManager.GetString("ColunaPermissao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefone.
        /// </summary>
        public static string ColunaTelefone {
            get {
                return ResourceManager.GetString("ColunaTelefone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + Adicionar usuário.
        /// </summary>
        public static string LinkAdicionarUsuario {
            get {
                return ResourceManager.GetString("LinkAdicionarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carregando lista usuários....
        /// </summary>
        public static string MensagemCarregando {
            get {
                return ResourceManager.GetString("MensagemCarregando", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alterando ativação do usuário....
        /// </summary>
        public static string MensagemDesativando {
            get {
                return ResourceManager.GetString("MensagemDesativando", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhum usuário foi encontrado.
        /// </summary>
        public static string NenhumUsuarioEncontrado {
            get {
                return ResourceManager.GetString("NenhumUsuarioEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao tentar realizar esta operação.
        /// </summary>
        public static string OperacaoMensagemErro {
            get {
                return ResourceManager.GetString("OperacaoMensagemErro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operação realizada com sucesso.
        /// </summary>
        public static string OperacaoMensagemSucesso {
            get {
                return ResourceManager.GetString("OperacaoMensagemSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista de usuários cadastrados no sistema.
        /// </summary>
        public static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ativar usuário.
        /// </summary>
        public static string TitleAtivar {
            get {
                return ResourceManager.GetString("TitleAtivar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desativar usuário.
        /// </summary>
        public static string TitleDesativar {
            get {
                return ResourceManager.GetString("TitleDesativar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar usuário.
        /// </summary>
        public static string TitleEditar {
            get {
                return ResourceManager.GetString("TitleEditar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista Usuários Cadastrados.
        /// </summary>
        public static string TituloTela {
            get {
                return ResourceManager.GetString("TituloTela", resourceCulture);
            }
        }
    }
}
