//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TGV.IPEFAE.Web.Resources.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class _Contato {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _Contato() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TGV.IPEFAE.Web.Resources.Shared._Contato", typeof(_Contato).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contato.
        /// </summary>
        public static string Contato {
            get {
                return ResourceManager.GetString("Contato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviar.
        /// </summary>
        public static string ContatoBotaoEnviar {
            get {
                return ResourceManager.GetString("ContatoBotaoEnviar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deslize para enviar.
        /// </summary>
        public static string ContatoCaptchaObrigatorio {
            get {
                return ResourceManager.GetString("ContatoCaptchaObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digite seu e-mail..
        /// </summary>
        public static string ContatoEmailObrigatorio {
            get {
                return ResourceManager.GetString("ContatoEmailObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seu e-mail *.
        /// </summary>
        public static string ContatoEmailPlaceHolder {
            get {
                return ResourceManager.GetString("ContatoEmailPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Av. Dr. Oscar Pirajá Martins, 340 - São João da Boa Vista - SP.
        /// </summary>
        public static string ContatoEnderecoIPEFAE {
            get {
                return ResourceManager.GetString("ContatoEnderecoIPEFAE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formato de e-mail inválido.
        /// </summary>
        public static string ContatoFormatoInvalidoEmail {
            get {
                return ResourceManager.GetString("ContatoFormatoInvalidoEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formato de telefone inválido.
        /// </summary>
        public static string ContatoFormatoInvalidoTelefone {
            get {
                return ResourceManager.GetString("ContatoFormatoInvalidoTelefone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fale conosco... deixe sua mensagem!.
        /// </summary>
        public static string ContatoMensagem {
            get {
                return ResourceManager.GetString("ContatoMensagem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digite a mensagem..
        /// </summary>
        public static string ContatoMensagemObrigatoria {
            get {
                return ResourceManager.GetString("ContatoMensagemObrigatoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sua mensagem *.
        /// </summary>
        public static string ContatoMensagemPlaceHolder {
            get {
                return ResourceManager.GetString("ContatoMensagemPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digite seu nome..
        /// </summary>
        public static string ContatoNomeObrigatorio {
            get {
                return ResourceManager.GetString("ContatoNomeObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seu nome *.
        /// </summary>
        public static string ContatoNomePlaceHolder {
            get {
                return ResourceManager.GetString("ContatoNomePlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O e-mail é obrigatório.
        /// </summary>
        public static string ContatoObrigatorioEmail {
            get {
                return ResourceManager.GetString("ContatoObrigatorioEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A mensagem é obrigatória.
        /// </summary>
        public static string ContatoObrigatorioMensagem {
            get {
                return ResourceManager.GetString("ContatoObrigatorioMensagem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome é obrigatório.
        /// </summary>
        public static string ContatoObrigatorioNome {
            get {
                return ResourceManager.GetString("ContatoObrigatorioNome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O telefone é obrigatório.
        /// </summary>
        public static string ContatoObrigatorioTelefone {
            get {
                return ResourceManager.GetString("ContatoObrigatorioTelefone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contato enviado com sucesso.
        /// </summary>
        public static string ContatoSucesso {
            get {
                return ResourceManager.GetString("ContatoSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (19) 3622-3119.
        /// </summary>
        public static string ContatoTelefoneIPEFAE {
            get {
                return ResourceManager.GetString("ContatoTelefoneIPEFAE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digite seu telefone..
        /// </summary>
        public static string ContatoTelefoneObrigatorio {
            get {
                return ResourceManager.GetString("ContatoTelefoneObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seu telefone *.
        /// </summary>
        public static string ContatoTelefonePlaceHolder {
            get {
                return ResourceManager.GetString("ContatoTelefonePlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pode enviar.
        /// </summary>
        public static string ContatoUnlockFinal {
            get {
                return ResourceManager.GetString("ContatoUnlockFinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to deslize para enviar.
        /// </summary>
        public static string ContatoUnlockInicial {
            get {
                return ResourceManager.GetString("ContatoUnlockInicial", resourceCulture);
            }
        }
    }
}
