//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TGV.IPEFAE.Web.Resources.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class _DadosEstagiario {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _DadosEstagiario() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TGV.IPEFAE.Web.Resources.Shared._DadosEstagiario", typeof(_DadosEstagiario).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        public static string BotaoCancelar {
            get {
                return ResourceManager.GetString("BotaoCancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar.
        /// </summary>
        public static string BotaoConfirmar {
            get {
                return ResourceManager.GetString("BotaoConfirmar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to do Currículo.
        /// </summary>
        public static string BotaoPDFCurriculo {
            get {
                return ResourceManager.GetString("BotaoPDFCurriculo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gerar PDF.
        /// </summary>
        public static string BotaoPDFGerarPDF {
            get {
                return ResourceManager.GetString("BotaoPDFGerarPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currículo.
        /// </summary>
        public static string BotaoPreviewCurriculo {
            get {
                return ResourceManager.GetString("BotaoPreviewCurriculo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualizar.
        /// </summary>
        public static string BotaoPreviewVisualizar {
            get {
                return ResourceManager.GetString("BotaoPreviewVisualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvar.
        /// </summary>
        public static string BotaoSalvar {
            get {
                return ResourceManager.GetString("BotaoSalvar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voltar.
        /// </summary>
        public static string BotaoVoltar {
            get {
                return ResourceManager.GetString("BotaoVoltar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bairro.
        /// </summary>
        public static string LabelBairro {
            get {
                return ResourceManager.GetString("LabelBairro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carteira de Trabalho Nº.
        /// </summary>
        public static string LabelCarteiraTrabalho {
            get {
                return ResourceManager.GetString("LabelCarteiraTrabalho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Série.
        /// </summary>
        public static string LabelCarteiraTrabalhoSerie {
            get {
                return ResourceManager.GetString("LabelCarteiraTrabalhoSerie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UF.
        /// </summary>
        public static string LabelCarteiraTrabalhoUF {
            get {
                return ResourceManager.GetString("LabelCarteiraTrabalhoUF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefone 02.
        /// </summary>
        public static string LabelCelular {
            get {
                return ResourceManager.GetString("LabelCelular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CEP.
        /// </summary>
        public static string LabelCEP {
            get {
                return ResourceManager.GetString("LabelCEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cidade.
        /// </summary>
        public static string LabelCidade {
            get {
                return ResourceManager.GetString("LabelCidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complemento.
        /// </summary>
        public static string LabelComplemento {
            get {
                return ResourceManager.GetString("LabelComplemento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirme sua senha.
        /// </summary>
        public static string LabelConfirmacaoSenha {
            get {
                return ResourceManager.GetString("LabelConfirmacaoSenha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPF.
        /// </summary>
        public static string LabelCPF {
            get {
                return ResourceManager.GetString("LabelCPF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Expedição.
        /// </summary>
        public static string LabelDataExpedicao {
            get {
                return ResourceManager.GetString("LabelDataExpedicao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Nascimento.
        /// </summary>
        public static string LabelDataNascimento {
            get {
                return ResourceManager.GetString("LabelDataNascimento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digite sua senha para realizar seu cadastro.
        /// </summary>
        public static string LabelDigiteSuaSenha {
            get {
                return ResourceManager.GetString("LabelDigiteSuaSenha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (ela não aparecerá em seu cv).
        /// </summary>
        public static string LabelDigiteSuaSenhaAlerta {
            get {
                return ResourceManager.GetString("LabelDigiteSuaSenhaAlerta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo.
        /// </summary>
        public static string LabelEJA01 {
            get {
                return ResourceManager.GetString("LabelEJA01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ano.
        /// </summary>
        public static string LabelEJA02 {
            get {
                return ResourceManager.GetString("LabelEJA02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ano.
        /// </summary>
        public static string LabelEM01 {
            get {
                return ResourceManager.GetString("LabelEM01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string LabelEmail {
            get {
                return ResourceManager.GetString("LabelEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endereço.
        /// </summary>
        public static string LabelEndereco {
            get {
                return ResourceManager.GetString("LabelEndereco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semestre.
        /// </summary>
        public static string LabelES01 {
            get {
                return ResourceManager.GetString("LabelES01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modalidade.
        /// </summary>
        public static string LabelES02 {
            get {
                return ResourceManager.GetString("LabelES02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        public static string LabelEstado {
            get {
                return ResourceManager.GetString("LabelEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado Civil.
        /// </summary>
        public static string LabelEstadoCivil {
            get {
                return ResourceManager.GetString("LabelEstadoCivil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo.
        /// </summary>
        public static string LabelET01 {
            get {
                return ResourceManager.GetString("LabelET01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qtdade Filhos.
        /// </summary>
        public static string LabelFilhos {
            get {
                return ResourceManager.GetString("LabelFilhos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foto.
        /// </summary>
        public static string LabelFoto {
            get {
                return ResourceManager.GetString("LabelFoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  anos.
        /// </summary>
        public static string LabelIdadeAnos {
            get {
                return ResourceManager.GetString("LabelIdadeAnos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Somente arquivos de imagem (png ou jpg).
        /// </summary>
        public static string LabelInfoFoto {
            get {
                return ResourceManager.GetString("LabelInfoFoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Início (mês e ano).
        /// </summary>
        public static string LabelMesAnoInicio {
            get {
                return ResourceManager.GetString("LabelMesAnoInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previsão Término (mês e ano).
        /// </summary>
        public static string LabelMesAnoPrevisaoTermino {
            get {
                return ResourceManager.GetString("LabelMesAnoPrevisaoTermino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome Completo.
        /// </summary>
        public static string LabelNomeCompleto {
            get {
                return ResourceManager.GetString("LabelNomeCompleto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome do Curso.
        /// </summary>
        public static string LabelNomeCurso {
            get {
                return ResourceManager.GetString("LabelNomeCurso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome da Escola Completo.
        /// </summary>
        public static string LabelNomeEscola {
            get {
                return ResourceManager.GetString("LabelNomeEscola", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número.
        /// </summary>
        public static string LabelNumeroEndereco {
            get {
                return ResourceManager.GetString("LabelNumeroEndereco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Período.
        /// </summary>
        public static string LabelPeriodo {
            get {
                return ResourceManager.GetString("LabelPeriodo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Possui Deficiência?.
        /// </summary>
        public static string LabelPossuiDeficiencia {
            get {
                return ResourceManager.GetString("LabelPossuiDeficiencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qual?.
        /// </summary>
        public static string LabelPossuiDeficienciaQual {
            get {
                return ResourceManager.GetString("LabelPossuiDeficienciaQual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Possui Experiência Profissional?.
        /// </summary>
        public static string LabelPossuiExperienciaProfissional {
            get {
                return ResourceManager.GetString("LabelPossuiExperienciaProfissional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RG.
        /// </summary>
        public static string LabelRG {
            get {
                return ResourceManager.GetString("LabelRG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione um tipo.
        /// </summary>
        public static string LabelSelecioneET01 {
            get {
                return ResourceManager.GetString("LabelSelecioneET01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sexo.
        /// </summary>
        public static string LabelSexo {
            get {
                return ResourceManager.GetString("LabelSexo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefone 01.
        /// </summary>
        public static string LabelTelefone {
            get {
                return ResourceManager.GetString("LabelTelefone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo Ensino.
        /// </summary>
        public static string LabelTipoEnsino {
            get {
                return ResourceManager.GetString("LabelTipoEnsino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cursos e Capacitações.
        /// </summary>
        public static string LegendaCursosCapacitacoes {
            get {
                return ResourceManager.GetString("LegendaCursosCapacitacoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dados Escolares.
        /// </summary>
        public static string LegendaDadosEscolares {
            get {
                return ResourceManager.GetString("LegendaDadosEscolares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dados Pessoais.
        /// </summary>
        public static string LegendaDadosPessoais {
            get {
                return ResourceManager.GetString("LegendaDadosPessoais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experiência Profissional.
        /// </summary>
        public static string LegendaExperienciaProfissional {
            get {
                return ResourceManager.GetString("LegendaExperienciaProfissional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objetivos no Estágio.
        /// </summary>
        public static string LegendaObjetivosEstagio {
            get {
                return ResourceManager.GetString("LegendaObjetivosEstagio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conhecimentos Práticos, Outros Conhecimentos e Informações Adicionais.
        /// </summary>
        public static string LegendaOutrosConhecimentos {
            get {
                return ResourceManager.GetString("LegendaOutrosConhecimentos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvando curriculo....
        /// </summary>
        public static string MensagemBlockUISalvar {
            get {
                return ResourceManager.GetString("MensagemBlockUISalvar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operação realizada com sucesso.
        /// </summary>
        public static string MensagemCurriculoSalvoSucesso {
            get {
                return ResourceManager.GetString("MensagemCurriculoSalvoSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este e-mail já está cadastrado no sistema. Caso tenha esquecido sua senha, volte a tela anterior e solicite-a com este e-mail..
        /// </summary>
        public static string MensagemEmailExistente {
            get {
                return ResourceManager.GetString("MensagemEmailExistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carregando foto....
        /// </summary>
        public static string MensagemRealizandoUpload {
            get {
                return ResourceManager.GetString("MensagemRealizandoUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validando e-mail ....
        /// </summary>
        public static string MensagemValidandoEmail {
            get {
                return ResourceManager.GetString("MensagemValidandoEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auditiva.
        /// </summary>
        public static string OptionAuditiva {
            get {
                return ResourceManager.GetString("OptionAuditiva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Casado.
        /// </summary>
        public static string OptionCasado {
            get {
                return ResourceManager.GetString("OptionCasado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Divorciado.
        /// </summary>
        public static string OptionDivorciado {
            get {
                return ResourceManager.GetString("OptionDivorciado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EJA (Ensino de Jovens e Adultos).
        /// </summary>
        public static string OptionEJA {
            get {
                return ResourceManager.GetString("OptionEJA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ensino Fundamental.
        /// </summary>
        public static string OptionEJAEF {
            get {
                return ResourceManager.GetString("OptionEJAEF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ensino Médio.
        /// </summary>
        public static string OptionEJAEM {
            get {
                return ResourceManager.GetString("OptionEJAEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ensino Médio.
        /// </summary>
        public static string OptionEnsinoMedio {
            get {
                return ResourceManager.GetString("OptionEnsinoMedio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ensino Superior.
        /// </summary>
        public static string OptionEnsinoSuperior {
            get {
                return ResourceManager.GetString("OptionEnsinoSuperior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feminino.
        /// </summary>
        public static string OptionFeminino {
            get {
                return ResourceManager.GetString("OptionFeminino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Física.
        /// </summary>
        public static string OptionFisica {
            get {
                return ResourceManager.GetString("OptionFisica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integral.
        /// </summary>
        public static string OptionIntegral {
            get {
                return ResourceManager.GetString("OptionIntegral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manhã.
        /// </summary>
        public static string OptionManha {
            get {
                return ResourceManager.GetString("OptionManha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Masculino.
        /// </summary>
        public static string OptionMasculino {
            get {
                return ResourceManager.GetString("OptionMasculino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mental.
        /// </summary>
        public static string OptionMental {
            get {
                return ResourceManager.GetString("OptionMental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EAD (à distância).
        /// </summary>
        public static string OptionModalidadeEAD {
            get {
                return ResourceManager.GetString("OptionModalidadeEAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presencial.
        /// </summary>
        public static string OptionModalidadePresencial {
            get {
                return ResourceManager.GetString("OptionModalidadePresencial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Múltipla.
        /// </summary>
        public static string OptionMultipla {
            get {
                return ResourceManager.GetString("OptionMultipla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não.
        /// </summary>
        public static string OptionNao {
            get {
                return ResourceManager.GetString("OptionNao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noite.
        /// </summary>
        public static string OptionNoite {
            get {
                return ResourceManager.GetString("OptionNoite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outros.
        /// </summary>
        public static string OptionOutros {
            get {
                return ResourceManager.GetString("OptionOutros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sim.
        /// </summary>
        public static string OptionSim {
            get {
                return ResourceManager.GetString("OptionSim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solteiro.
        /// </summary>
        public static string OptionSolteiro {
            get {
                return ResourceManager.GetString("OptionSolteiro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarde.
        /// </summary>
        public static string OptionTarde {
            get {
                return ResourceManager.GetString("OptionTarde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Técnico / Profissionalizante.
        /// </summary>
        public static string OptionTecnico {
            get {
                return ResourceManager.GetString("OptionTecnico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Módulo.
        /// </summary>
        public static string OptionTipoModulo {
            get {
                return ResourceManager.GetString("OptionTipoModulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semestre.
        /// </summary>
        public static string OptionTipoSemestre {
            get {
                return ResourceManager.GetString("OptionTipoSemestre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Termo.
        /// </summary>
        public static string OptionTipoTermo {
            get {
                return ResourceManager.GetString("OptionTipoTermo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual.
        /// </summary>
        public static string OptionVisual {
            get {
                return ResourceManager.GetString("OptionVisual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viuvo.
        /// </summary>
        public static string OptionViuvo {
            get {
                return ResourceManager.GetString("OptionViuvo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirme sua senha.
        /// </summary>
        public static string PlaceHolderConfirmacaoSenha {
            get {
                return ResourceManager.GetString("PlaceHolderConfirmacaoSenha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descreva seus objetivos no estágio.
        /// </summary>
        public static string PlaceHolderObjetivosEstagio {
            get {
                return ResourceManager.GetString("PlaceHolderObjetivosEstagio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digite sua senha aqui.
        /// </summary>
        public static string PlaceHolderSenha {
            get {
                return ResourceManager.GetString("PlaceHolderSenha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastro de Estágio.
        /// </summary>
        public static string TituloTela {
            get {
                return ResourceManager.GetString("TituloTela", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O arquivo da foto deve ser jpg, bmp ou png e ter no máximo 2MB.
        /// </summary>
        public static string ValidacaoArquivoFormatoInvalido {
            get {
                return ResourceManager.GetString("ValidacaoArquivoFormatoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A foto é obrigatória.
        /// </summary>
        public static string ValidacaoArquivoObrigatorio {
            get {
                return ResourceManager.GetString("ValidacaoArquivoObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As atividades desenvolvidas na empresa é obrigatório.
        /// </summary>
        public static string ValidacaoAtividadesDesenvolvidasObrigatorio {
            get {
                return ResourceManager.GetString("ValidacaoAtividadesDesenvolvidasObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O bairro é obrigatório.
        /// </summary>
        public static string ValidacaoBairroObrigatorio {
            get {
                return ResourceManager.GetString("ValidacaoBairroObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O cargo exercido na empresa é obrigatório.
        /// </summary>
        public static string ValidacaoCargoObrigatorio {
            get {
                return ResourceManager.GetString("ValidacaoCargoObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O número da carteira de trabalho é obrigatório.
        /// </summary>
        public static string ValidacaoCarteiraTrabalhoNumeroObrigatorio {
            get {
                return ResourceManager.GetString("ValidacaoCarteiraTrabalhoNumeroObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A série da carteira de trabalho é obrigatória.
        /// </summary>
        public static string ValidacaoCarteiraTrabalhoSerieObrigatorio {
            get {
                return ResourceManager.GetString("ValidacaoCarteiraTrabalhoSerieObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O estado da carteira de trabalho é obrigatório.
        /// </summary>
        public static string ValidacaoCarteiraTrabalhoUFObrigatorio {
            get {
                return ResourceManager.GetString("ValidacaoCarteiraTrabalhoUFObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O CEP é obrigatório.
        /// </summary>
        public static string ValidacaoCEPObrigatorio {
            get {
                return ResourceManager.GetString("ValidacaoCEPObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A cidade é obrigatória.
        /// </summary>
        public static string ValidacaoCidadeObrigatorio {
            get {
                return ResourceManager.GetString("ValidacaoCidadeObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A confirmação da senha é obrigatória.
        /// </summary>
        public static string ValidacaoConfirmacaSenhaObrigatorio {
            get {
                return ResourceManager.GetString("ValidacaoConfirmacaSenhaObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O CPF é obrigatório.
        /// </summary>
        public static string ValidacaoCPFObrigatorio {
            get {
                return ResourceManager.GetString("ValidacaoCPFObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data de expedição é obrigatória.
        /// </summary>
        public static string ValidacaoDataExpedicaoObrigatoria {
            get {
                return ResourceManager.GetString("ValidacaoDataExpedicaoObrigatoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formato da data de início (mês/ano) está inválido.
        /// </summary>
        public static string ValidacaoDataInicioDEFormatoInvalido {
            get {
                return ResourceManager.GetString("ValidacaoDataInicioDEFormatoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data de início (mês/ano) é obrigatória.
        /// </summary>
        public static string ValidacaoDataInicioDEObrigatorio {
            get {
                return ResourceManager.GetString("ValidacaoDataInicioDEObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O formato da data de nascimento está inválido.
        /// </summary>
        public static string ValidacaoDataNascFormatoInvalido {
            get {
                return ResourceManager.GetString("ValidacaoDataNascFormatoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data de nascimento é obrigatória.
        /// </summary>
        public static string ValidacaoDataNascObrigatorio {
            get {
                return ResourceManager.GetString("ValidacaoDataNascObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formato da data de término (mês/ano) está inválido.
        /// </summary>
        public static string ValidacaoDataTerminoDEFormatoInvalido {
            get {
                return ResourceManager.GetString("ValidacaoDataTerminoDEFormatoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data de término (mês/ano) é obrigatória.
        /// </summary>
        public static string ValidacaoDataTerminoDEObrigatorio {
            get {
                return ResourceManager.GetString("ValidacaoDataTerminoDEObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Previsão de Término deve ser maior do que a Data de Início.
        /// </summary>
        public static string ValidacaoDataTerminoMaiorDataInicio {
            get {
                return ResourceManager.GetString("ValidacaoDataTerminoMaiorDataInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este item é obrigatório.
        /// </summary>
        public static string ValidacaoDe01Obrigatorio {
            get {
                return ResourceManager.GetString("ValidacaoDe01Obrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este item é obrigatório.
        /// </summary>
        public static string ValidacaoDe02Obrigatorio {
            get {
                return ResourceManager.GetString("ValidacaoDe02Obrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qual a deficiência é obrigatória.
        /// </summary>
        public static string ValidacaoDeficienciaQualObrigatorio {
            get {
                return ResourceManager.GetString("ValidacaoDeficienciaQualObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A duração é obrigatória.
        /// </summary>
        public static string ValidacaoDuracaoObrigatorio {
            get {
                return ResourceManager.GetString("ValidacaoDuracaoObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O e-mail é obrigatório.
        /// </summary>
        public static string ValidacaoEmailObrigatorio {
            get {
                return ResourceManager.GetString("ValidacaoEmailObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O endereço é obrigatório.
        /// </summary>
        public static string ValidacaoEnderecoObrigatorio {
            get {
                return ResourceManager.GetString("ValidacaoEnderecoObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O estado é obrigatório.
        /// </summary>
        public static string ValidacaoEstadoObrigatorio {
            get {
                return ResourceManager.GetString("ValidacaoEstadoObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O formato da data de expedição está inválido.
        /// </summary>
        public static string ValidacaoFormatoDataExpedicaoInvalido {
            get {
                return ResourceManager.GetString("ValidacaoFormatoDataExpedicaoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O formato do e-mail está inválido.
        /// </summary>
        public static string ValidacaoFormatoEmailInvalido {
            get {
                return ResourceManager.GetString("ValidacaoFormatoEmailInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome do curso é obrigatório.
        /// </summary>
        public static string ValidacaoNomeCursoObrigatorio {
            get {
                return ResourceManager.GetString("ValidacaoNomeCursoObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome da empresa é obrigatório.
        /// </summary>
        public static string ValidacaoNomeEmpresaObrigatorio {
            get {
                return ResourceManager.GetString("ValidacaoNomeEmpresaObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome da escola é obrigatório.
        /// </summary>
        public static string ValidacaoNomeEscolaObrigatorio {
            get {
                return ResourceManager.GetString("ValidacaoNomeEscolaObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome é obrigatório.
        /// </summary>
        public static string ValidacaoNomeObrigatorio {
            get {
                return ResourceManager.GetString("ValidacaoNomeObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O número do endereço é obrigatório.
        /// </summary>
        public static string ValidacaoNroEnderecoObrigatorioObrigatorio {
            get {
                return ResourceManager.GetString("ValidacaoNroEnderecoObrigatorioObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O período é obrigatório.
        /// </summary>
        public static string ValidacaoPeriodoObrigatorio {
            get {
                return ResourceManager.GetString("ValidacaoPeriodoObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A quantidade de filhos é obrigatória.
        /// </summary>
        public static string ValidacaoQtdadeFilhosObrigatorio {
            get {
                return ResourceManager.GetString("ValidacaoQtdadeFilhosObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O RG é obrigatório.
        /// </summary>
        public static string ValidacaoRGObrigatorio {
            get {
                return ResourceManager.GetString("ValidacaoRGObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha e sua confirmação devem ser iguais.
        /// </summary>
        public static string ValidacaoSenhaConfirmacaoDiferente {
            get {
                return ResourceManager.GetString("ValidacaoSenhaConfirmacaoDiferente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha é obrigatória.
        /// </summary>
        public static string ValidacaoSenhaObrigatorio {
            get {
                return ResourceManager.GetString("ValidacaoSenhaObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O seu gênero é obrigatório.
        /// </summary>
        public static string ValidacaoSexoObrigatorio {
            get {
                return ResourceManager.GetString("ValidacaoSexoObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O telefone 01 é obrigatório.
        /// </summary>
        public static string ValidacaoTelefoneObrigatorio {
            get {
                return ResourceManager.GetString("ValidacaoTelefoneObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de ensino é obrigatório.
        /// </summary>
        public static string ValidacaoTipoEnsinoObrigatorio {
            get {
                return ResourceManager.GetString("ValidacaoTipoEnsinoObrigatorio", resourceCulture);
            }
        }
    }
}
