//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TGV.IPEFAE.Web.Resources.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class _DadosInscrito {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _DadosInscrito() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TGV.IPEFAE.Web.Resources.Shared._DadosInscrito", typeof(_DadosInscrito).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O bairro é obrigatório.
        /// </summary>
        public static string BairroObrigatorio {
            get {
                return ResourceManager.GetString("BairroObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvar.
        /// </summary>
        public static string BotaoSalvar {
            get {
                return ResourceManager.GetString("BotaoSalvar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voltar.
        /// </summary>
        public static string BotaoVoltar {
            get {
                return ResourceManager.GetString("BotaoVoltar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A opção é obrigatória.
        /// </summary>
        public static string CargoObrigatorio {
            get {
                return ResourceManager.GetString("CargoObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O CEP é obrigatório.
        /// </summary>
        public static string CepObrigatorio {
            get {
                return ResourceManager.GetString("CepObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A cidade é obrigatória.
        /// </summary>
        public static string CidadeObrigatorio {
            get {
                return ResourceManager.GetString("CidadeObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O formato do CPF está inválido.
        /// </summary>
        public static string CpfFormatoInvalido {
            get {
                return ResourceManager.GetString("CpfFormatoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPF já cadastrado para este .
        /// </summary>
        public static string CpfJaExistente {
            get {
                return ResourceManager.GetString("CpfJaExistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O CPF é obrigatório.
        /// </summary>
        public static string CpfObrigatorio {
            get {
                return ResourceManager.GetString("CpfObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Data de Nascimento está inválida.
        /// </summary>
        public static string DataNascFormatoInvalido {
            get {
                return ResourceManager.GetString("DataNascFormatoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data de nascimento é obrigatória.
        /// </summary>
        public static string DataNascObrigatorio {
            get {
                return ResourceManager.GetString("DataNascObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O formato do e-mail está inválido.
        /// </summary>
        public static string EmailFormatoInvalido {
            get {
                return ResourceManager.GetString("EmailFormatoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O e-mail é obrigatório.
        /// </summary>
        public static string EmailObrigatorio {
            get {
                return ResourceManager.GetString("EmailObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O endereço é obrigatório.
        /// </summary>
        public static string EnderecoObrigatorio {
            get {
                return ResourceManager.GetString("EnderecoObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado Emissor.
        /// </summary>
        public static string EstadoEmissor {
            get {
                return ResourceManager.GetString("EstadoEmissor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A quantidade de filhos menores é obrigatório.
        /// </summary>
        public static string FilhosMenoresObrigatorio {
            get {
                return ResourceManager.GetString("FilhosMenoresObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ativo?.
        /// </summary>
        public static string LabelAtivo {
            get {
                return ResourceManager.GetString("LabelAtivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bairro.
        /// </summary>
        public static string LabelBairro {
            get {
                return ResourceManager.GetString("LabelBairro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefone 02.
        /// </summary>
        public static string LabelCelular {
            get {
                return ResourceManager.GetString("LabelCelular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CEP.
        /// </summary>
        public static string LabelCEP {
            get {
                return ResourceManager.GetString("LabelCEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cidade.
        /// </summary>
        public static string LabelCidade {
            get {
                return ResourceManager.GetString("LabelCidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complemento.
        /// </summary>
        public static string LabelComplemento {
            get {
                return ResourceManager.GetString("LabelComplemento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPF.
        /// </summary>
        public static string LabelCPF {
            get {
                return ResourceManager.GetString("LabelCPF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Nascimento.
        /// </summary>
        public static string LabelDataNascimento {
            get {
                return ResourceManager.GetString("LabelDataNascimento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destro / Canhoto.
        /// </summary>
        public static string LabelDestroCanhoto {
            get {
                return ResourceManager.GetString("LabelDestroCanhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string LabelEmail {
            get {
                return ResourceManager.GetString("LabelEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endereço.
        /// </summary>
        public static string LabelEndereco {
            get {
                return ResourceManager.GetString("LabelEndereco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (rua e número).
        /// </summary>
        public static string LabelEnderecoSub {
            get {
                return ResourceManager.GetString("LabelEnderecoSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        public static string LabelEstado {
            get {
                return ResourceManager.GetString("LabelEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado Civil.
        /// </summary>
        public static string LabelEstadoCivil {
            get {
                return ResourceManager.GetString("LabelEstadoCivil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantidade de filhos menores 18 anos.
        /// </summary>
        public static string LabelFilhosMenores {
            get {
                return ResourceManager.GetString("LabelFilhosMenores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Isento?.
        /// </summary>
        public static string LabelIsento {
            get {
                return ResourceManager.GetString("LabelIsento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome Completo.
        /// </summary>
        public static string LabelNomeCompleto {
            get {
                return ResourceManager.GetString("LabelNomeCompleto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número.
        /// </summary>
        public static string LabelNumeroEndereco {
            get {
                return ResourceManager.GetString("LabelNumeroEndereco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Possui alguma deficiência?.
        /// </summary>
        public static string LabelPossuiDeficiencia {
            get {
                return ResourceManager.GetString("LabelPossuiDeficiencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qual?.
        /// </summary>
        public static string LabelPossuiDeficienciaQual {
            get {
                return ResourceManager.GetString("LabelPossuiDeficienciaQual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documento de Identidade.
        /// </summary>
        public static string LabelRG {
            get {
                return ResourceManager.GetString("LabelRG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefone 01.
        /// </summary>
        public static string LabelTelefone {
            get {
                return ResourceManager.GetString("LabelTelefone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condição Especial Realização Prova Objetiva?.
        /// </summary>
        public static string LabelTratamentoEspecial {
            get {
                return ResourceManager.GetString("LabelTratamentoEspecial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qual?.
        /// </summary>
        public static string LabelTratamentoEspecialQual {
            get {
                return ResourceManager.GetString("LabelTratamentoEspecialQual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dados Pessoais.
        /// </summary>
        public static string LegendDadosPessoais {
            get {
                return ResourceManager.GetString("LegendDadosPessoais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opção de Cargo.
        /// </summary>
        public static string LegendOpcaoCargo {
            get {
                return ResourceManager.GetString("LegendOpcaoCargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvando dados do inscrito....
        /// </summary>
        public static string MensagemSalvando {
            get {
                return ResourceManager.GetString("MensagemSalvando", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operação realizada com sucesso.
        /// </summary>
        public static string MensagemSucessoSalvar {
            get {
                return ResourceManager.GetString("MensagemSucessoSalvar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome completo é obrigatório.
        /// </summary>
        public static string NomeObrigatorio {
            get {
                return ResourceManager.GetString("NomeObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O número do endereço é obrigatório.
        /// </summary>
        public static string NroEnderecoObrigatorio {
            get {
                return ResourceManager.GetString("NroEnderecoObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auditiva.
        /// </summary>
        public static string OptionAuditiva {
            get {
                return ResourceManager.GetString("OptionAuditiva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canhoto.
        /// </summary>
        public static string OptionCanhoto {
            get {
                return ResourceManager.GetString("OptionCanhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Casado.
        /// </summary>
        public static string OptionCasado {
            get {
                return ResourceManager.GetString("OptionCasado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destro.
        /// </summary>
        public static string OptionDestro {
            get {
                return ResourceManager.GetString("OptionDestro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Divorciado.
        /// </summary>
        public static string OptionDivorciado {
            get {
                return ResourceManager.GetString("OptionDivorciado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Física.
        /// </summary>
        public static string OptionFisica {
            get {
                return ResourceManager.GetString("OptionFisica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mental.
        /// </summary>
        public static string OptionMental {
            get {
                return ResourceManager.GetString("OptionMental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Múltipla.
        /// </summary>
        public static string OptionMultipla {
            get {
                return ResourceManager.GetString("OptionMultipla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não.
        /// </summary>
        public static string OptionNao {
            get {
                return ResourceManager.GetString("OptionNao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outros.
        /// </summary>
        public static string OptionOutros {
            get {
                return ResourceManager.GetString("OptionOutros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sim.
        /// </summary>
        public static string OptionSim {
            get {
                return ResourceManager.GetString("OptionSim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solteiro.
        /// </summary>
        public static string OptionSolteiro {
            get {
                return ResourceManager.GetString("OptionSolteiro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual.
        /// </summary>
        public static string OptionVisual {
            get {
                return ResourceManager.GetString("OptionVisual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viuvo.
        /// </summary>
        public static string OptionViuvo {
            get {
                return ResourceManager.GetString("OptionViuvo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O tipo de deficiência é obrigatório.
        /// </summary>
        public static string QualDeficienciaObrigatorio {
            get {
                return ResourceManager.GetString("QualDeficienciaObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O tipo de tratamento especial é obrigatório.
        /// </summary>
        public static string QualTratamentoEspecialObrigatorio {
            get {
                return ResourceManager.GetString("QualTratamentoEspecialObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O documento de identidade é obrigatório.
        /// </summary>
        public static string RgObrigatorio {
            get {
                return ResourceManager.GetString("RgObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O telefone é obrigatório.
        /// </summary>
        public static string TelefoneObrigatorio {
            get {
                return ResourceManager.GetString("TelefoneObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se necessita de tratamento especial é obrigatório.
        /// </summary>
        public static string TratamentoEspecialObrigatorio {
            get {
                return ResourceManager.GetString("TratamentoEspecialObrigatorio", resourceCulture);
            }
        }
    }
}
