//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TGV.IPEFAE.Web.Resources.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class _Layout {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _Layout() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TGV.IPEFAE.Web.Resources.Shared._Layout", typeof(_Layout).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string MenuAdmin {
            get {
                return ResourceManager.GetString("MenuAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Áreas.
        /// </summary>
        public static string MenuAreas {
            get {
                return ResourceManager.GetString("MenuAreas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concursos.
        /// </summary>
        public static string MenuAreasItemConcursos {
            get {
                return ResourceManager.GetString("MenuAreasItemConcursos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastre seu Currículo.
        /// </summary>
        public static string MenuAreasItemCurriculo {
            get {
                return ResourceManager.GetString("MenuAreasItemCurriculo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estágio.
        /// </summary>
        public static string MenuAreasItemEstagios {
            get {
                return ResourceManager.GetString("MenuAreasItemEstagios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estágio Transparência.
        /// </summary>
        public static string MenuAreasItemEstagiosTransparencia {
            get {
                return ResourceManager.GetString("MenuAreasItemEstagiosTransparencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuários.
        /// </summary>
        public static string MenuAreasItemUsuario {
            get {
                return ResourceManager.GetString("MenuAreasItemUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vestibulares.
        /// </summary>
        public static string MenuAreasItemVestibulares {
            get {
                return ResourceManager.GetString("MenuAreasItemVestibulares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contato.
        /// </summary>
        public static string MenuContato {
            get {
                return ResourceManager.GetString("MenuContato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string MenuHome {
            get {
                return ResourceManager.GetString("MenuHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serviços.
        /// </summary>
        public static string MenuServicos {
            get {
                return ResourceManager.GetString("MenuServicos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPEFAE.
        /// </summary>
        public static string MetaContent {
            get {
                return ResourceManager.GetString("MetaContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instituto de Pesquisas Econômicas - .
        /// </summary>
        public static string SubTitulo {
            get {
                return ResourceManager.GetString("SubTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPEFAE.
        /// </summary>
        public static string SubTituloIPEFAE {
            get {
                return ResourceManager.GetString("SubTituloIPEFAE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPEFAE.
        /// </summary>
        public static string Titulo {
            get {
                return ResourceManager.GetString("Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPEFAE.
        /// </summary>
        public static string TituloFooter {
            get {
                return ResourceManager.GetString("TituloFooter", resourceCulture);
            }
        }
    }
}
