//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TGV.IPEFAE.Web.Resources.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class _ModalLogin {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _ModalLogin() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TGV.IPEFAE.Web.Resources.Shared._ModalLogin", typeof(_ModalLogin).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrar.
        /// </summary>
        public static string BotaoConfirmarValue {
            get {
                return ResourceManager.GetString("BotaoConfirmarValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seu@email.com.br.
        /// </summary>
        public static string EmailPlaceHolder {
            get {
                return ResourceManager.GetString("EmailPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro ao tentar realizar o login.
        /// </summary>
        public static string ErroLogin {
            get {
                return ResourceManager.GetString("ErroLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Realizando login do usuário....
        /// </summary>
        public static string MensagemBlockUILogin {
            get {
                return ResourceManager.GetString("MensagemBlockUILogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saindo do sistema....
        /// </summary>
        public static string MensagemBlockUILogoff {
            get {
                return ResourceManager.GetString("MensagemBlockUILogoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O e-mail é obrigatório.
        /// </summary>
        public static string ObrigatorioEmail {
            get {
                return ResourceManager.GetString("ObrigatorioEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formato de e-mail inválido.
        /// </summary>
        public static string ObrigatorioFormatoEmail {
            get {
                return ResourceManager.GetString("ObrigatorioFormatoEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha é obrigatória.
        /// </summary>
        public static string ObrigatorioSenha {
            get {
                return ResourceManager.GetString("ObrigatorioSenha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário não cadastrado ou senha incorreta.
        /// </summary>
        public static string SenhaErrada {
            get {
                return ResourceManager.GetString("SenhaErrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sua senha.
        /// </summary>
        public static string SenhaPlaceHolder {
            get {
                return ResourceManager.GetString("SenhaPlaceHolder", resourceCulture);
            }
        }
    }
}
