//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TGV.IPEFAE.Web.Resources.Admin.Concurso.Empresa {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Cadastro {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Cadastro() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TGV.IPEFAE.Web.Resources.Admin.Concurso.Empresa.Cadastro", typeof(Cadastro).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvar.
        /// </summary>
        public static string BotaoSalvar {
            get {
                return ResourceManager.GetString("BotaoSalvar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agência.
        /// </summary>
        public static string LabelAgencia {
            get {
                return ResourceManager.GetString("LabelAgencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (somente números - sem dígito).
        /// </summary>
        public static string LabelAgenciaComentario {
            get {
                return ResourceManager.GetString("LabelAgenciaComentario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ativo.
        /// </summary>
        public static string LabelAtivo {
            get {
                return ResourceManager.GetString("LabelAtivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banco.
        /// </summary>
        public static string LabelBanco {
            get {
                return ResourceManager.GetString("LabelBanco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CNPJ.
        /// </summary>
        public static string LabelCNPJ {
            get {
                return ResourceManager.GetString("LabelCNPJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conta Corrente.
        /// </summary>
        public static string LabelConta {
            get {
                return ResourceManager.GetString("LabelConta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (somente números - com dígito).
        /// </summary>
        public static string LabelContaComentario {
            get {
                return ResourceManager.GetString("LabelContaComentario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convênio.
        /// </summary>
        public static string LabelConvenio {
            get {
                return ResourceManager.GetString("LabelConvenio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convênio Cobrança.
        /// </summary>
        public static string LabelConvenioCobranca {
            get {
                return ResourceManager.GetString("LabelConvenioCobranca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string LabelNome {
            get {
                return ResourceManager.GetString("LabelNome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Razão Social.
        /// </summary>
        public static string LabelRazaoSocial {
            get {
                return ResourceManager.GetString("LabelRazaoSocial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Situação.
        /// </summary>
        public static string LabelSituacao {
            get {
                return ResourceManager.GetString("LabelSituacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvando dados da empresa....
        /// </summary>
        public static string MensagemSalvando {
            get {
                return ResourceManager.GetString("MensagemSalvando", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00.000.000/0000-00.
        /// </summary>
        public static string PlaceHolderCNPJ {
            get {
                return ResourceManager.GetString("PlaceHolderCNPJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Razão Social da Empresa.
        /// </summary>
        public static string PlaceHolderRazaoSocial {
            get {
                return ResourceManager.GetString("PlaceHolderRazaoSocial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro ao salvar os dados da empresa.
        /// </summary>
        public static string SalvarErro {
            get {
                return ResourceManager.GetString("SalvarErro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operação realizada com sucesso.
        /// </summary>
        public static string SalvarSucesso {
            get {
                return ResourceManager.GetString("SalvarSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastro Empresa.
        /// </summary>
        public static string TituloTela {
            get {
                return ResourceManager.GetString("TituloTela", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A agência é obrigatória.
        /// </summary>
        public static string ValidacaoAgenciaObrigatorio {
            get {
                return ResourceManager.GetString("ValidacaoAgenciaObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O banco é obrigatório.
        /// </summary>
        public static string ValidacaoBancoObrigatorio {
            get {
                return ResourceManager.GetString("ValidacaoBancoObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O cnpj é obrigatório.
        /// </summary>
        public static string ValidacaoCNPJObrigatorio {
            get {
                return ResourceManager.GetString("ValidacaoCNPJObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A conta corrente é obrigatória.
        /// </summary>
        public static string ValidacaoContaObrigatorio {
            get {
                return ResourceManager.GetString("ValidacaoContaObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O número do convênio é obrigatório.
        /// </summary>
        public static string ValidacaoConvenioObrigatorio {
            get {
                return ResourceManager.GetString("ValidacaoConvenioObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome é obrigatório.
        /// </summary>
        public static string ValidacaoNomeObrigatorio {
            get {
                return ResourceManager.GetString("ValidacaoNomeObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A razão social é obrigatória.
        /// </summary>
        public static string ValidacaoRazaoSocialObrigatorio {
            get {
                return ResourceManager.GetString("ValidacaoRazaoSocialObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voltar a lista.
        /// </summary>
        public static string VoltarLista {
            get {
                return ResourceManager.GetString("VoltarLista", resourceCulture);
            }
        }
    }
}
