//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TGV.IPEFAE.Web.Resources.Admin.Concurso.Empresa {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TGV.IPEFAE.Web.Resources.Admin.Concurso.Empresa.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agência - Conta.
        /// </summary>
        public static string ColunaAgenciaConta {
            get {
                return ResourceManager.GetString("ColunaAgenciaConta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ativo.
        /// </summary>
        public static string ColunaAtivo {
            get {
                return ResourceManager.GetString("ColunaAtivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banco.
        /// </summary>
        public static string ColunaBanco {
            get {
                return ResourceManager.GetString("ColunaBanco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CNPJ.
        /// </summary>
        public static string ColunaCNPJ {
            get {
                return ResourceManager.GetString("ColunaCNPJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string ColunaNome {
            get {
                return ResourceManager.GetString("ColunaNome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Razão Social.
        /// </summary>
        public static string ColunaRazaoSocial {
            get {
                return ResourceManager.GetString("ColunaRazaoSocial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + Adicionar empresa.
        /// </summary>
        public static string LinkAdicionarEmpresa {
            get {
                return ResourceManager.GetString("LinkAdicionarEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carregando lista empresas....
        /// </summary>
        public static string MensagemCarregando {
            get {
                return ResourceManager.GetString("MensagemCarregando", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alterando ativação do empresa....
        /// </summary>
        public static string MensagemDesativando {
            get {
                return ResourceManager.GetString("MensagemDesativando", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhuma empresa foi encontrada.
        /// </summary>
        public static string NenhumaEmpresaEncontrada {
            get {
                return ResourceManager.GetString("NenhumaEmpresaEncontrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao tentar realizar esta operação.
        /// </summary>
        public static string OperacaoMensagemErro {
            get {
                return ResourceManager.GetString("OperacaoMensagemErro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operação realizada com sucesso.
        /// </summary>
        public static string OperacaoMensagemSucesso {
            get {
                return ResourceManager.GetString("OperacaoMensagemSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista de empresas cadastradas no sistema.
        /// </summary>
        public static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ativar empresa.
        /// </summary>
        public static string TitleAtivar {
            get {
                return ResourceManager.GetString("TitleAtivar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desativar empresa.
        /// </summary>
        public static string TitleDesativar {
            get {
                return ResourceManager.GetString("TitleDesativar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar empresa.
        /// </summary>
        public static string TitleEditar {
            get {
                return ResourceManager.GetString("TitleEditar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista Empresas Cadastradas.
        /// </summary>
        public static string TituloTela {
            get {
                return ResourceManager.GetString("TituloTela", resourceCulture);
            }
        }
    }
}
