//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TGV.IPEFAE.Web.Resources.Email {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class _HtmlContato {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _HtmlContato() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TGV.IPEFAE.Web.Resources.Email._HtmlContato", typeof(_HtmlContato).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Você realizou um contato em nosso site utilizando o e-mail:.
        /// </summary>
        public static string CorpoInfoEmail {
            get {
                return ResourceManager.GetString("CorpoInfoEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Um de nossos atendentes irá analisar o seu caso e lhe retornará o mais breve possível..
        /// </summary>
        public static string CorpoInfoResposta {
            get {
                return ResourceManager.GetString("CorpoInfoResposta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefone:.
        /// </summary>
        public static string CorpoInfoTelefone {
            get {
                return ResourceManager.GetString("CorpoInfoTelefone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Olá.
        /// </summary>
        public static string CorpoSaudacao {
            get {
                return ResourceManager.GetString("CorpoSaudacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPEFAE.
        /// </summary>
        public static string NomeFrom {
            get {
                return ResourceManager.GetString("NomeFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [IPEFAE] Contato - {0}.
        /// </summary>
        public static string TituloEmail {
            get {
                return ResourceManager.GetString("TituloEmail", resourceCulture);
            }
        }
    }
}
