//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TGV.IPEFAE.Web.BL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class banco
    {
        public banco()
        {
            this.colaborador = new HashSet<colaborador>();
        }
    
        public int id { get; set; }
        public string codigo { get; set; }
        public string nome { get; set; }
        public int ordem { get; set; }
        public bool ativo { get; set; }
    
        public virtual ICollection<colaborador> colaborador { get; set; }
    }
}
