//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TGV.IPEFAE.Web.BL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class concurso
    {
        public concurso()
        {
            this.concurso_colaborador = new HashSet<concurso_colaborador>();
            this.concurso_funcao = new HashSet<concurso_funcao>();
        }
    
        public int id { get; set; }
        public string nome { get; set; }
        public bool ativo { get; set; }
    
        public virtual ICollection<concurso_colaborador> concurso_colaborador { get; set; }
        public virtual ICollection<concurso_funcao> concurso_funcao { get; set; }
    }
}
