//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TGV.IPEFAE.Web.BL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class funcao
    {
        public System.Guid id { get; set; }
        public string nome { get; set; }
        public int codigo { get; set; }
        public int cbo { get; set; }
        public bool is_active { get; set; }
    }
}
