//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TGV.IPEFAE.Web.BL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class irpf
    {
        public int id { get; set; }
        public decimal valor_min { get; set; }
        public decimal valor_max { get; set; }
        public decimal taxa { get; set; }
        public decimal deducao { get; set; }
        public bool ativo { get; set; }
    }
}
