//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TGV.IPEFAE.Web.BL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class neotrading
    {
        public int id { get; set; }
        public string email { get; set; }
        public string nome { get; set; }
        public string codigo { get; set; }
        public string senha { get; set; }
        public System.DateTime data_entrega { get; set; }
        public bool is_active { get; set; }
    }
}
