//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TGV.IPEFAE.Web.BL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_cci_concurso_cargo_inscrito
    {
        public int con_idt_concurso { get; set; }
        public int cco_idt_cargo_concurso { get; set; }
        public int ico_idt_inscrito_concurso { get; set; }
    
        public virtual tb_cco_cargo_concurso tb_cco_cargo_concurso { get; set; }
        public virtual tb_con_concurso tb_con_concurso { get; set; }
        public virtual tb_ico_inscrito_concurso tb_ico_inscrito_concurso { get; set; }
    }
}
