//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TGV.IPEFAE.Web.BL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_con_concurso
    {
        public tb_con_concurso()
        {
            this.tb_can_concurso_anexo = new HashSet<tb_can_concurso_anexo>();
            this.tb_cci_concurso_cargo_inscrito = new HashSet<tb_cci_concurso_cargo_inscrito>();
            this.tb_cco_cargo_concurso = new HashSet<tb_cco_cargo_concurso>();
            this.tb_rec_recurso = new HashSet<tb_rec_recurso>();
            this.tb_ico_inscrito_concurso = new HashSet<tb_ico_inscrito_concurso>();
        }
    
        public int con_idt_concurso { get; set; }
        public int emp_idt_empresa { get; set; }
        public int tlc_idt_tipo_layout_concurso { get; set; }
        public string con_nom_concurso { get; set; }
        public System.DateTime con_dat_concurso { get; set; }
        public System.DateTime con_dat_inicio_classificacao { get; set; }
        public System.DateTime con_dat_inicio_comprovante { get; set; }
        public System.DateTime con_dat_inicio_isento { get; set; }
        public System.DateTime con_dat_encerramento_inscricoes { get; set; }
        public System.DateTime con_dat_encerramento_comprovante { get; set; }
        public System.DateTime con_dat_encerramento_isento { get; set; }
        public Nullable<System.DateTime> con_dat_encerramento { get; set; }
        public bool con_bit_encerrado { get; set; }
        public bool con_bit_inscricao_online { get; set; }
        public bool con_bit_ativo { get; set; }
        public System.DateTime con_dat_boleto { get; set; }
    
        public virtual ICollection<tb_can_concurso_anexo> tb_can_concurso_anexo { get; set; }
        public virtual ICollection<tb_cci_concurso_cargo_inscrito> tb_cci_concurso_cargo_inscrito { get; set; }
        public virtual ICollection<tb_cco_cargo_concurso> tb_cco_cargo_concurso { get; set; }
        public virtual tb_tlc_tipo_layout_concurso tb_tlc_tipo_layout_concurso { get; set; }
        public virtual ICollection<tb_rec_recurso> tb_rec_recurso { get; set; }
        public virtual tb_emp_empresa tb_emp_empresa { get; set; }
        public virtual ICollection<tb_ico_inscrito_concurso> tb_ico_inscrito_concurso { get; set; }
    }
}
