//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TGV.IPEFAE.Web.BL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_can_concurso_anexo
    {
        public int can_idt_concurso_anexo { get; set; }
        public int con_idt_concurso { get; set; }
        public int tca_idt_tipo_concurso_anexo { get; set; }
        public string can_nom_concurso_anexo { get; set; }
        public string can_des_path_arquivo { get; set; }
        public System.DateTime can_dat_publicacao { get; set; }
        public Nullable<System.DateTime> can_dat_inicio_recurso { get; set; }
        public Nullable<System.DateTime> can_dat_fim_recurso { get; set; }
        public bool can_bit_tem_recurso { get; set; }
        public bool can_bit_ativo { get; set; }
    
        public virtual tb_con_concurso tb_con_concurso { get; set; }
    }
}
