//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TGV.IPEFAE.Web.BL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_cco_cargo_concurso
    {
        public tb_cco_cargo_concurso()
        {
            this.tb_cci_concurso_cargo_inscrito = new HashSet<tb_cci_concurso_cargo_inscrito>();
        }
    
        public int cco_idt_cargo_concurso { get; set; }
        public int con_idt_concurso { get; set; }
        public string cco_nom_cargo_concurso { get; set; }
        public Nullable<decimal> cco_num_valor_inscricao { get; set; }
        public bool cco_bit_ativo { get; set; }
    
        public virtual ICollection<tb_cci_concurso_cargo_inscrito> tb_cci_concurso_cargo_inscrito { get; set; }
        public virtual tb_con_concurso tb_con_concurso { get; set; }
    }
}
