//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TGV.IPEFAE.Web.BL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ema_email
    {
        public System.DateTime ema_dat_email { get; set; }
        public string ema_des_from { get; set; }
        public string ema_des_to { get; set; }
        public string ema_des_cc { get; set; }
        public string ema_des_bcc { get; set; }
        public string ema_des_assunto { get; set; }
        public string ema_des_corpo { get; set; }
        public bool ema_bit_anexo { get; set; }
    }
}
