//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TGV.IPEFAE.Web.BL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_emp_empresa
    {
        public tb_emp_empresa()
        {
            this.tb_con_concurso = new HashSet<tb_con_concurso>();
        }
    
        public int emp_idt_empresa { get; set; }
        public string emp_nom_empresa { get; set; }
        public short emp_num_banco { get; set; }
        public int emp_num_convenio { get; set; }
        public Nullable<int> emp_num_convenio_cobranca { get; set; }
        public string emp_des_cnpj { get; set; }
        public string emp_des_razao_social { get; set; }
        public string emp_des_agencia { get; set; }
        public string emp_des_conta_corrente { get; set; }
        public bool emp_bit_ativo { get; set; }
    
        public virtual ICollection<tb_con_concurso> tb_con_concurso { get; set; }
    }
}
