//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TGV.IPEFAE.Web.BL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_idt_inscrito_dados_prova
    {
        public int ico_idt_inscrito_concurso { get; set; }
        public Nullable<System.DateTime> idt_dat_prova { get; set; }
        public string idt_des_local { get; set; }
        public string idt_des_sala { get; set; }
        public string idt_des_andar { get; set; }
        public string idt_des_endereco { get; set; }
        public string idt_des_numero { get; set; }
        public string idt_des_bairro { get; set; }
        public string idt_des_cidade { get; set; }
        public string idt_des_cep { get; set; }
        public bool idt_bit_ativo { get; set; }
    
        public virtual tb_ico_inscrito_concurso tb_ico_inscrito_concurso { get; set; }
    }
}
