//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TGV.IPEFAE.Web.BL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_icv_inscrito_concurso_vestibular
    {
        public int ico_idt_inscrito_concurso { get; set; }
        public Nullable<int> icv_idt_opcao_2 { get; set; }
        public Nullable<int> icv_idt_opcao_3 { get; set; }
        public int icv_num_local_prova { get; set; }
        public int icv_num_data_prova { get; set; }
        public string icv_des_nome_indicado_por { get; set; }
        public string icv_des_curso_indicado_por { get; set; }
        public string icv_des_semestre_curso_indicado_por { get; set; }
        public Nullable<int> icv_num_renda_mensal { get; set; }
        public Nullable<int> icv_num_tipo_ensino_medio { get; set; }
        public Nullable<int> icv_num_tipo_concluiu_ensino_medio { get; set; }
        public Nullable<int> icv_num_tipo_concluiu_ensino_fundamental { get; set; }
        public Nullable<int> icv_num_atividade_remunerada { get; set; }
        public Nullable<int> icv_num_escolaridade_pai { get; set; }
        public Nullable<int> icv_num_escolaridade_mae { get; set; }
        public Nullable<int> icv_num_optar_unifae { get; set; }
        public Nullable<int> icv_num_optar_curso { get; set; }
        public Nullable<int> icv_num_conhecimento_unifae { get; set; }
        public string icv_des_conhecimento_unifae_outros { get; set; }
        public System.DateTime icv_dat_aceito_termos { get; set; }
        public bool icv_bit_eh_masculino { get; set; }
        public bool icv_bit_ativo { get; set; }
    
        public virtual tb_ico_inscrito_concurso tb_ico_inscrito_concurso { get; set; }
    }
}
