//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TGV.IPEFAE.Web.BL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ler_log_erro
    {
        public long ler_idt_log_erro { get; set; }
        public Nullable<int> usu_idt_usuario { get; set; }
        public System.DateTime ler_dat_erro { get; set; }
        public Nullable<int> ler_num_codigo_erro { get; set; }
        public string ler_des_nome_metodo { get; set; }
        public string ler_des_source { get; set; }
        public string ler_des_inner_exception { get; set; }
        public string ler_des_mensagem { get; set; }
        public string ler_des_stack_trace { get; set; }
        public string ler_des_tipo_exception { get; set; }
        public string ler_des_url { get; set; }
    }
}
