//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TGV.IPEFAE.Web.BL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_rec_recurso
    {
        public int rec_idt_recurso { get; set; }
        public int con_idt_concurso { get; set; }
        public int ico_idt_inscrito_concurso { get; set; }
        public int sre_idt_status_recurso { get; set; }
        public Nullable<int> usu_idt_usuario { get; set; }
        public System.DateTime rec_dat_abertura { get; set; }
        public Nullable<System.DateTime> rec_dat_atendimento { get; set; }
        public string rec_des_comentario { get; set; }
        public string rec_des_mensagem { get; set; }
        public bool rec_bit_ativo { get; set; }
    
        public virtual tb_sre_status_recurso tb_sre_status_recurso { get; set; }
        public virtual tb_usu_usuario tb_usu_usuario { get; set; }
        public virtual tb_con_concurso tb_con_concurso { get; set; }
        public virtual tb_ico_inscrito_concurso tb_ico_inscrito_concurso { get; set; }
    }
}
