//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TGV.IPEFAE.Web.BL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_tlc_tipo_layout_concurso
    {
        public tb_tlc_tipo_layout_concurso()
        {
            this.tb_con_concurso = new HashSet<tb_con_concurso>();
        }
    
        public int tlc_idt_tipo_layout_concurso { get; set; }
        public string tlc_nom_tipo_layout_concurso { get; set; }
        public bool tlc_bit_ativo { get; set; }
    
        public virtual ICollection<tb_con_concurso> tb_con_concurso { get; set; }
    }
}
