//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TGV.IPEFAE.Web.BL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ueo_usuario_estagio_outros
    {
        public int ueo_idt_usuario_estagio_outros { get; set; }
        public int ues_idt_usuario_estagio { get; set; }
        public string ueo_nom_usuario_estagio_outros { get; set; }
        public string ueo_des_duracao { get; set; }
        public bool ueo_bit_curso { get; set; }
        public bool ueo_bit_ativo { get; set; }
    
        public virtual tb_ues_usuario_estagio tb_ues_usuario_estagio { get; set; }
    }
}
