//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TGV.IPEFAE.Web.BL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ues_usuario_estagio
    {
        public tb_ues_usuario_estagio()
        {
            this.tb_uee_usuario_estagio_experiencia = new HashSet<tb_uee_usuario_estagio_experiencia>();
            this.tb_ueo_usuario_estagio_outros = new HashSet<tb_ueo_usuario_estagio_outros>();
        }
    
        public int ues_idt_usuario_estagio { get; set; }
        public int cid_idt_cidade_endereco { get; set; }
        public Nullable<int> est_idt_estado_carteira_trabalho { get; set; }
        public int ued_idt_usuario_estagio_dados_escolares { get; set; }
        public string ues_nom_usuario_estagio { get; set; }
        public int ues_num_quantidade_filhos { get; set; }
        public string ues_des_cpf { get; set; }
        public string ues_des_rg { get; set; }
        public string ues_des_email { get; set; }
        public string ues_des_senha { get; set; }
        public string ues_des_carteira_trabalho_numero { get; set; }
        public string ues_des_carteira_trabalho_serie { get; set; }
        public string ues_des_endereco { get; set; }
        public int ues_des_numero_endereco { get; set; }
        public string ues_des_bairro { get; set; }
        public string ues_des_complemento { get; set; }
        public string ues_des_cep { get; set; }
        public string ues_des_telefone { get; set; }
        public string ues_des_celular { get; set; }
        public string ues_des_objetivos { get; set; }
        public string ues_des_observacoes_admin { get; set; }
        public string ues_flg_estado_civil { get; set; }
        public string ues_flg_deficiencia { get; set; }
        public string ues_flg_motivo_desativacao { get; set; }
        public System.DateTime ues_dat_nascimento { get; set; }
        public System.DateTime ues_dat_rg_expedicao { get; set; }
        public System.DateTime ues_dat_criacao_cv { get; set; }
        public System.DateTime ues_dat_ultima_atualizacao { get; set; }
        public bool ues_bit_considerar_busca { get; set; }
        public bool ues_bit_estagiando { get; set; }
        public bool ues_bit_possui_deficiencia { get; set; }
        public bool ues_bit_possui_experiencia_profissional { get; set; }
        public bool ues_bit_masculino { get; set; }
        public bool ues_bit_tem_foto { get; set; }
        public bool ues_bit_ativo { get; set; }
    
        public virtual tb_cid_cidade tb_cid_cidade { get; set; }
        public virtual tb_est_estado tb_est_estado { get; set; }
        public virtual tb_ued_usuario_estagio_dados_escolares tb_ued_usuario_estagio_dados_escolares { get; set; }
        public virtual ICollection<tb_uee_usuario_estagio_experiencia> tb_uee_usuario_estagio_experiencia { get; set; }
        public virtual ICollection<tb_ueo_usuario_estagio_outros> tb_ueo_usuario_estagio_outros { get; set; }
    }
}
