//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TGV.IPEFAE.Web.BL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ued_usuario_estagio_dados_escolares
    {
        public tb_ued_usuario_estagio_dados_escolares()
        {
            this.tb_ues_usuario_estagio = new HashSet<tb_ues_usuario_estagio>();
        }
    
        public int ued_idt_usuario_estagio_dados_escolares { get; set; }
        public int ued_num_ano_semestre { get; set; }
        public string ued_des_nome_escola { get; set; }
        public string ued_des_nome_curso { get; set; }
        public string ued_flg_periodo { get; set; }
        public string ued_flg_tipo_dados_escolares { get; set; }
        public string ued_flg_tipo_profissionalizante { get; set; }
        public Nullable<int> ued_num_mes_inicio { get; set; }
        public int ued_num_ano_inicio { get; set; }
        public Nullable<int> ued_num_mes_termino { get; set; }
        public int ued_num_ano_termino { get; set; }
        public Nullable<bool> ued_bit_ead { get; set; }
        public bool ued_bit_ativo { get; set; }
    
        public virtual tb_ued_usuario_estagio_dados_escolares tb_ued_usuario_estagio_dados_escolares1 { get; set; }
        public virtual tb_ued_usuario_estagio_dados_escolares tb_ued_usuario_estagio_dados_escolares2 { get; set; }
        public virtual ICollection<tb_ues_usuario_estagio> tb_ues_usuario_estagio { get; set; }
    }
}
