//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TGV.IPEFAE.Web.BL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_uee_usuario_estagio_experiencia
    {
        public int uee_idt_usuario_estagio_experiencia { get; set; }
        public int ues_idt_usuario_estagio { get; set; }
        public Nullable<int> uee_num_mes_inicio { get; set; }
        public Nullable<int> uee_num_ano_inicio { get; set; }
        public Nullable<int> uee_num_mes_termino { get; set; }
        public Nullable<int> uee_num_ano_termino { get; set; }
        public string uee_des_nome_empresa { get; set; }
        public string uee_des_cargo { get; set; }
        public string uee_des_atividades_desenvolvidas { get; set; }
        public bool uee_bit_ativo { get; set; }
    
        public virtual tb_ues_usuario_estagio tb_ues_usuario_estagio { get; set; }
    }
}
