//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TGV.IPEFAE.Web.BL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_usu_usuario
    {
        public tb_usu_usuario()
        {
            this.tb_rec_recurso = new HashSet<tb_rec_recurso>();
        }
    
        public int usu_idt_usuario { get; set; }
        public int per_idt_permissao { get; set; }
        public string usu_nom_usuario { get; set; }
        public string usu_des_email { get; set; }
        public string usu_des_senha { get; set; }
        public long usu_num_telefone { get; set; }
        public bool usu_bit_ativo { get; set; }
    
        public virtual ICollection<tb_rec_recurso> tb_rec_recurso { get; set; }
    }
}
