var cursosScript = {
    "1": "Administração",
    "2": "Administração Pública",
    "3": "Agronegócio",
    "4": "Agronomia (ou Engenharia Agronômica)",
    "5": "Alimentos",
    "6": "Análise de Sistemas & Tecnologia da Informação",
    "7": "Antropologia",
    "8": "Aquicultura",
    "9": "Arqueologia",
    "10": "Arquitetura",
    "11": "Arquivologia",
    "12": "Artes Cênicas",
    "13": "Artes Plásticas",
    "14": "Artes Visuais",
    "15": "Astronomia",
    "16": "Automação de Escritório (ou Secretariado)",
    "17": "Automação Industrial",
    "18": "Biblioteconomia",
    "19": "Biocombustíveis",
    "20": "Bioenergia Sucro-Alcooleira",
    "21": "Bioengenharia (ou Engenharia Biológica)",
    "22": "Biologia (ou Ciências Biológicas)",
    "23": "Biologia Marinha",
    "24": "Biomedicina",
    "25": "Bioquímica",
    "26": "Biotecnologia",
    "27": "Biotecnologia (ou Engenharia Biotecnológica)",
    "28": "Botânica",
    "29": "Ciência da Informação",
    "30": "Ciência dos Alimentos",
    "31": "Ciência dos Materiais",
    "32": "Ciência e Tecnologia",
    "33": "Ciências Ambientais",
    "34": "Ciências Atuariais",
    "35": "Ciências Contábeis (ou Contabilidade)",
    "36": "Ciências da Atividade Física",
    "37": "Ciências Econômicas (ou Economia)",
    "38": "Ciências Exatas (licenciatura)",
    "39": "Ciências Moleculares ou Biomoleculares",
    "40": "Ciências Naturais",
    "41": "Ciências Políticas (ou Ciências do Estado)",
    "42": "Ciências sociais (ou Sociologia)",
    "43": "Ciências do Esporte",
    "44": "Cinema",
    "45": "Comércio exterior",
    "46": "Computação Científica",
    "47": "Computação (licenciatura)",
    "48": "Comunicação Social",
    "49": "Construção Civil",
    "50": "Cooperativismo",
    "51": "Cosmetologia e Estética (ou Estética e Cosmética)",
    "52": "Dança",
    "53": "Defesa e Gestão Estratégica Internacional",
    "54": "Desenho Industrial (ou Design Gráfico)",
    "55": "Design",
    "56": "Design de Interiores",
    "57": "Design de Jogos Digitais",
    "58": "Design de Moda",
    "59": "Direito",
    "60": "Ecologia",
    "61": "Editoração (ou Produção Editorial)",
    "62": "Educação Artística",
    "63": "Educação Física - Bacharelado",
    "64": "Educação Física - Licenciatura",
    "65": "Educação Musical - Licenciatura",
    "66": "Eletrônica",
    "67": "Eletrônica Embarcada (ou Autotrônica)",
    "68": "Enfermagem",
    "69": "Engenharia Aeroespacial",
    "70": "Engenharia Aeronáutica",
    "71": "Engenharia Agrícola",
    "72": "Engenharia Ambiental",
    "73": "Engenharia Biofísica",
    "74": "Engenharia Biomédica",
    "75": "Engenharia Cartográfica",
    "76": "Engenharia Civil",
    "77": "Engenharia da Qualidade",
    "78": "Engenharia de Agrimensura",
    "79": "Engenharia de Alimentos",
    "80": "Engenharia de Áudio",
    "81": "Engenharia de Computação",
    "82": "Engenharia de Controle e Automação",
    "83": "Engenharia de Instrumentação (ou Engenharia de Controle e Automação ou Robótica)",
    "84": "Engenharia de Manutenção",
    "85": "Engenharia de Materiais",
    "86": "Engenharia de Minas",
    "87": "Engenharia de Pesca",
    "88": "Engenharia de Petróleo",
    "89": "Engenharia de Produção",
    "90": "Engenharia de Serviços",
    "91": "Engenharia de Sistemas",
    "92": "Engenharia de Sistemas Eletrônicos",
    "93": "Engenharia de Software",
    "94": "Engenharia de Tecidos",
    "95": "Engenharia de Telecomunicações",
    "96": "Engenharia de Transportes",
    "97": "Engenharia Econômica",
    "98": "Engenharia Elétrica (ou Engenharia Energética)",
    "99": "Engenharia Eletrônica",
    "100": "Engenharia Estrutural",
    "101": "Engenharia Física",
    "102": "Engenharia Florestal",
    "103": "Engenharia Geográfica",
    "104": "Engenharia Geológica",
    "105": "Engenharia Hidráulica",
    "106": "Engenharia Humana",
    "107": "Engenharia Industrial",
    "108": "Engenharia Industrial Madeireira",
    "109": "Engenharia Mecânica",
    "110": "Engenharia Mecatrônica",
    "111": "Engenharia Metalúrgica",
    "112": "Engenharia Militar",
    "113": "Engenharia Naval e Oceânica",
    "114": "Engenharia Nuclear",
    "115": "Engenharia Óptica",
    "116": "Engenharia Química",
    "117": "Engenharia Sanitária",
    "118": "Engenharia Têxtil",
    "119": "Engenharia Urbana",
    "120": "Engenharia de Informação",
    "121": "Engenharia de Manufatura",
    "122": "Engenharia Multimídia",
    "123": "Escultura",
    "124": "Esportes",
    "125": "Estatística",
    "126": "Estudos Literários",
    "127": "Eventos",
    "128": "Farmácia (ou Farmacêutica)",
    "129": "Filosofia",
    "130": "Física",
    "131": "Física Biológica",
    "132": "Física Computacional",
    "133": "Física Médica",
    "134": "Fisioterapia",
    "135": "Fonoaudiologia",
    "136": "Fotografia (ou Gravura)",
    "137": "Gastronomia",
    "138": "Geociências (ou Ciências da Terra)",
    "139": "Geofísica",
    "140": "Geografia",
    "141": "Geologia",
    "142": "Gerontologia",
    "143": "Gestão Ambiental",
    "144": "Gestão da Qualidade",
    "145": "Gestão de Comércio Internacional",
    "146": "Gestão de Empresas",
    "147": "Gestão de Políticas Públicas",
    "148": "Gestão Empresarial",
    "149": "Gestão da Produção de Calçados",
    "150": "História",
    "151": "História da Arte",
    "152": "Hotelaria",
    "153": "Informática Biomédica",
    "154": "Informática (ou Ciência da Computação)",
    "155": "Jornalismo",
    "156": "Lazer",
    "157": "Letras",
    "158": "Linguística",
    "159": "Logística",
    "160": "Logística e Transportes",
    "161": "Logística Aeroportuária",
    "162": "Manutenção Industrial (tecnologia)",
    "163": "Marketing (ou Propaganda)",
    "164": "Matemática",
    "165": "Matemática Aplicada",
    "166": "Matemática Computacional",
    "167": "Mecânica de Precisão (ou Mecatrônica)",
    "168": "Mecânica - Processos de Produção",
    "169": "Medicina",
    "170": "Medicina Veterinária",
    "171": "Meio Ambiente e Recursos Hídricos",
    "172": "Metalurgia",
    "173": "Meteorologia",
    "174": "Microbiologia (ou Imunologia)",
    "175": "Museologia",
    "176": "Música",
    "177": "Nutrição",
    "178": "Obstetrícia",
    "179": "Oceanografia (ou Oceanologia ou Ciência dos Mares)",
    "180": "Odontologia",
    "181": "Paisagismo",
    "182": "Pedagogia",
    "183": "Pintura",
    "184": "Processamento de Dados",
    "185": "Processos Gerenciais",
    "186": "Produção",
    "187": "Produção de Materiais Plásticos",
    "188": "Produção Fonográfica",
    "189": "Produção Têxtil",
    "190": "Prospecção Geofísica",
    "191": "Psicologia",
    "192": "Psicopedagogia",
    "193": "Publicidade e Propaganda",
    "194": "Química",
    "195": "Química Ambiental",
    "196": "Química Industrial",
    "197": "Radialismo (ou Rádio & TV, ou Audiovisual)",
    "198": "Radiologia",
    "199": "Recursos Humanos",
    "200": "Relações Internacionais (ou Diplomacia)",
    "201": "Relações Públicas",
    "202": "Saneamento",
    "203": "Secretariado",
    "204": "Segurança da Informação",
    "205": "Serviço Social",
    "206": "Silvicultura",
    "207": "Sistemas de Informação",
    "208": "Teatro",
    "209": "Tecnologia da Informação",
    "210": "Telecomunicações",
    "211": "Telemática",
    "212": "Teologia",
    "213": "Terapia Ocupacional",
    "214": "Transporte Hidroviário (ou Transporte Marítimo)",
    "215": "Turismologia",
    "216": "Urbanismo",
    "217": "Zootecnia"
}