//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TGV.IPEFAE.Web.Resources.Concurso {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class _CartaoCandidato {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _CartaoCandidato() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TGV.IPEFAE.Web.Resources.Concurso._CartaoCandidato", typeof(_CartaoCandidato).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atente-se às informações contidas no Edital, pois é obrigação do candidato estar ciente a todas as normas ali estabelecidas.
        /// </summary>
        public static string LabelAtencao {
            get {
                return ResourceManager.GetString("LabelAtencao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EVITE ATRASOS! CHEGUE COM ANTECEDÊNCIA!.
        /// </summary>
        public static string LabelAtraso {
            get {
                return ResourceManager.GetString("LabelAtraso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IDENTIDADE:.
        /// </summary>
        public static string LabelIdentidade {
            get {
                return ResourceManager.GetString("LabelIdentidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSTITUTO DE PESQUISAS ECONÔMICAS - IPEFAE.
        /// </summary>
        public static string LabelIPEFAE {
            get {
                return ResourceManager.GetString("LabelIPEFAE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOME DO CANDIDATO:.
        /// </summary>
        public static string LabelNomeCandidato {
            get {
                return ResourceManager.GetString("LabelNomeCandidato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSCRIÇÃO Nº:.
        /// </summary>
        public static string LabelNumeroInscricao {
            get {
                return ResourceManager.GetString("LabelNumeroInscricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPÇÃO DE INSCRIÇÃO:.
        /// </summary>
        public static string LabelOpcaoInscricao {
            get {
                return ResourceManager.GetString("LabelOpcaoInscricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ANDAR:.
        /// </summary>
        public static string LabelProvaAndar {
            get {
                return ResourceManager.GetString("LabelProvaAndar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BAIRRO:.
        /// </summary>
        public static string LabelProvaBairro {
            get {
                return ResourceManager.GetString("LabelProvaBairro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CEP:.
        /// </summary>
        public static string LabelProvaCEP {
            get {
                return ResourceManager.GetString("LabelProvaCEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CIDADE:.
        /// </summary>
        public static string LabelProvaCidade {
            get {
                return ResourceManager.GetString("LabelProvaCidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATA:.
        /// </summary>
        public static string LabelProvaData {
            get {
                return ResourceManager.GetString("LabelProvaData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HORA:.
        /// </summary>
        public static string LabelProvaHora {
            get {
                return ResourceManager.GetString("LabelProvaHora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOCAL:.
        /// </summary>
        public static string LabelProvaLocal {
            get {
                return ResourceManager.GetString("LabelProvaLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOGRADOURO e Nº:.
        /// </summary>
        public static string LabelProvaLogradouro {
            get {
                return ResourceManager.GetString("LabelProvaLogradouro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SALA:.
        /// </summary>
        public static string LabelProvaSala {
            get {
                return ResourceManager.GetString("LabelProvaSala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DADOS DO CANDIDATO.
        /// </summary>
        public static string LegendDadosCandidato {
            get {
                return ResourceManager.GetString("LegendDadosCandidato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DADOS DA PROVA.
        /// </summary>
        public static string LegendDadosProva {
            get {
                return ResourceManager.GetString("LegendDadosProva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENDEREÇO DA REALIZAÇÃO DA PROVA.
        /// </summary>
        public static string LegendDadosProvaEndereco {
            get {
                return ResourceManager.GetString("LegendDadosProvaEndereco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CARTÃO DO CANDIDATO.
        /// </summary>
        public static string TituloTela {
            get {
                return ResourceManager.GetString("TituloTela", resourceCulture);
            }
        }
    }
}
