//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TGV.IPEFAE.Web.Resources.Concurso {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class _ClassificacaoResultado {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _ClassificacaoResultado() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TGV.IPEFAE.Web.Resources.Concurso._ClassificacaoResultado", typeof(_ClassificacaoResultado).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CE:.
        /// </summary>
        public static string LabelCE {
            get {
                return ResourceManager.GetString("LabelCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CG:.
        /// </summary>
        public static string LabelCG {
            get {
                return ResourceManager.GetString("LabelCG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLASSIFICAÇÃO:.
        /// </summary>
        public static string LabelClassificacao {
            get {
                return ResourceManager.GetString("LabelClassificacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PARA FINS DE COMPREENSÃO, ENTENDA-SE ONDE SE LÊ:.
        /// </summary>
        public static string LabelEntendimento {
            get {
                return ResourceManager.GetString("LabelEntendimento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CE: Quantidade de pontos em Conhecimentos Específicos (se houver).
        /// </summary>
        public static string LabelEntendimentoCE {
            get {
                return ResourceManager.GetString("LabelEntendimentoCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CG: Quantidade de pontos em Conhecimentos Gerais (se houver).
        /// </summary>
        public static string LabelEntendimentoCG {
            get {
                return ResourceManager.GetString("LabelEntendimentoCG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOTA: Soma dos pontos (conforme especificação do Edital).
        /// </summary>
        public static string LabelEntendimentoNota {
            get {
                return ResourceManager.GetString("LabelEntendimentoNota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PP: Pontuação da prova prática (se houver).
        /// </summary>
        public static string LabelEntendimentoPP {
            get {
                return ResourceManager.GetString("LabelEntendimentoPP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIT: Pontuação na avaliação de títulos (se houver).
        /// </summary>
        public static string LabelEntendimentoTIT {
            get {
                return ResourceManager.GetString("LabelEntendimentoTIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IDENTIDADE:.
        /// </summary>
        public static string LabelIdentidade {
            get {
                return ResourceManager.GetString("LabelIdentidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSTITUTO DE PESQUISAS ECONÔMICAS - IPEFAE.
        /// </summary>
        public static string LabelIPEFAE {
            get {
                return ResourceManager.GetString("LabelIPEFAE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOME DO CANDIDATO:.
        /// </summary>
        public static string LabelNomeCandidato {
            get {
                return ResourceManager.GetString("LabelNomeCandidato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOTA: .
        /// </summary>
        public static string LabelNota {
            get {
                return ResourceManager.GetString("LabelNota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSCRIÇÃO Nº:.
        /// </summary>
        public static string LabelNumeroInscricao {
            get {
                return ResourceManager.GetString("LabelNumeroInscricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPÇÃO DE INSCRIÇÃO:.
        /// </summary>
        public static string LabelOpcaoInscricao {
            get {
                return ResourceManager.GetString("LabelOpcaoInscricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PP:.
        /// </summary>
        public static string LabelPP {
            get {
                return ResourceManager.GetString("LabelPP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O SEU RESULTADO AINDA ESTÁ SENDO GERADO. POR FAVOR, AGUARDE!.
        /// </summary>
        public static string LabelSemClassificacao {
            get {
                return ResourceManager.GetString("LabelSemClassificacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SITUAÇÃO:.
        /// </summary>
        public static string LabelSituacao {
            get {
                return ResourceManager.GetString("LabelSituacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIT:.
        /// </summary>
        public static string LabelTIT {
            get {
                return ResourceManager.GetString("LabelTIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLASSIFICAÇÃO.
        /// </summary>
        public static string LegendClassificacao {
            get {
                return ResourceManager.GetString("LegendClassificacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DADOS DO CANDIDATO.
        /// </summary>
        public static string LegendDadosCandidato {
            get {
                return ResourceManager.GetString("LegendDadosCandidato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RESULTADO.
        /// </summary>
        public static string TituloTela {
            get {
                return ResourceManager.GetString("TituloTela", resourceCulture);
            }
        }
    }
}
