//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TGV.IPEFAE.Web.Resources.Concurso {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class _ListaPublicacoes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _ListaPublicacoes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TGV.IPEFAE.Web.Resources.Concurso._ListaPublicacoes", typeof(_ListaPublicacoes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classificação.
        /// </summary>
        public static string BotaoClassificacao {
            get {
                return ResourceManager.GetString("BotaoClassificacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cartão do Candidato.
        /// </summary>
        public static string BotaoComprovante {
            get {
                return ResourceManager.GetString("BotaoComprovante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cartão Candidato.
        /// </summary>
        public static string BotaoComprovanteMini {
            get {
                return ResourceManager.GetString("BotaoComprovanteMini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faça aqui sua inscrição.
        /// </summary>
        public static string BotaoInscricao {
            get {
                return ResourceManager.GetString("BotaoInscricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Isenção.
        /// </summary>
        public static string BotaoIsencao {
            get {
                return ResourceManager.GetString("BotaoIsencao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor Inscrição.
        /// </summary>
        public static string BotaoIsencaoValorInscricao {
            get {
                return ResourceManager.GetString("BotaoIsencaoValorInscricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Pagamento.
        /// </summary>
        public static string BotaoPagamentoOk {
            get {
                return ResourceManager.GetString("BotaoPagamentoOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2ª via.
        /// </summary>
        public static string BotaoSegundaVia {
            get {
                return ResourceManager.GetString("BotaoSegundaVia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to boleto.
        /// </summary>
        public static string BotaoSegundaViaBoleto {
            get {
                return ResourceManager.GetString("BotaoSegundaViaBoleto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualizar.
        /// </summary>
        public static string BotaoVisualizar {
            get {
                return ResourceManager.GetString("BotaoVisualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhum arquivo foi encontrado.
        /// </summary>
        public static string NenhumAnexoEncontrado {
            get {
                return ResourceManager.GetString("NenhumAnexoEncontrado", resourceCulture);
            }
        }
    }
}
