//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TGV.IPEFAE.Web.Resources.Concurso {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class _ModalBuscaInscrito {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _ModalBuscaInscrito() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TGV.IPEFAE.Web.Resources.Concurso._ModalBuscaInscrito", typeof(_ModalBuscaInscrito).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fechar.
        /// </summary>
        public static string BotaoCancelar {
            get {
                return ResourceManager.GetString("BotaoCancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gerar Boleto.
        /// </summary>
        public static string BotaoGerar {
            get {
                return ResourceManager.GetString("BotaoGerar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gerar Cartão.
        /// </summary>
        public static string BotaoGerarComprovante {
            get {
                return ResourceManager.GetString("BotaoGerarComprovante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obter Status.
        /// </summary>
        public static string BotaoGerarStatusPagamento {
            get {
                return ResourceManager.GetString("BotaoGerarStatusPagamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obter Classificação.
        /// </summary>
        public static string BotaoObterClassificacao {
            get {
                return ResourceManager.GetString("BotaoObterClassificacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O CPF é obrigatório.
        /// </summary>
        public static string CpfObrigatorio {
            get {
                return ResourceManager.GetString("CpfObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPF NÃO CADASTRADO PARA ESTE CONCURSO.
        /// </summary>
        public static string LabelCPFNaoEncontrado {
            get {
                return ResourceManager.GetString("LabelCPFNaoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digite seu CPF para gerar o boleto.
        /// </summary>
        public static string LabelDigiteCPF {
            get {
                return ResourceManager.GetString("LabelDigiteCPF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digite seu CPF para obter a classificação.
        /// </summary>
        public static string LabelDigiteCPFClassificacao {
            get {
                return ResourceManager.GetString("LabelDigiteCPFClassificacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digite seu CPF para gerar o comprovante.
        /// </summary>
        public static string LabelDigiteCPFComprovante {
            get {
                return ResourceManager.GetString("LabelDigiteCPFComprovante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digite seu CPF para obter o status do seu pagamento.
        /// </summary>
        public static string LabelDigiteCPFStatusPagamento {
            get {
                return ResourceManager.GetString("LabelDigiteCPFStatusPagamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O status do seu pagamento é: .
        /// </summary>
        public static string LabelStatusPagamentoResultado {
            get {
                return ResourceManager.GetString("LabelStatusPagamentoResultado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gerando boleto bancário ....
        /// </summary>
        public static string MensagemGerandoBoletoBancario {
            get {
                return ResourceManager.GetString("MensagemGerandoBoletoBancario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gerando classificação ....
        /// </summary>
        public static string MensagemGerandoClassificacao {
            get {
                return ResourceManager.GetString("MensagemGerandoClassificacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gerando cartão do candidato ....
        /// </summary>
        public static string MensagemGerandoComprovanteInscricao {
            get {
                return ResourceManager.GetString("MensagemGerandoComprovanteInscricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtendo status do pagamento ....
        /// </summary>
        public static string MensagemGerandoStatusPagamento {
            get {
                return ResourceManager.GetString("MensagemGerandoStatusPagamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtendo classificação....
        /// </summary>
        public static string MensagemObtendoClassificacao {
            get {
                return ResourceManager.GetString("MensagemObtendoClassificacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione uma matrícula.
        /// </summary>
        public static string MensagemSelecioneUmaMatricula {
            get {
                return ResourceManager.GetString("MensagemSelecioneUmaMatricula", resourceCulture);
            }
        }
    }
}
