//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TGV.IPEFAE.Web.Resources.Concurso {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class InscricaoConfirmacao {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InscricaoConfirmacao() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TGV.IPEFAE.Web.Resources.Concurso.InscricaoConfirmacao", typeof(InscricaoConfirmacao).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar Inscrição.
        /// </summary>
        public static string BotaoConfirmar {
            get {
                return ResourceManager.GetString("BotaoConfirmar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voltar.
        /// </summary>
        public static string BotaoVoltar {
            get {
                return ResourceManager.GetString("BotaoVoltar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leia atentamento ao termo de responsabilidade.
        /// </summary>
        public static string H1LeiaAtentamente {
            get {
                return ResourceManager.GetString("H1LeiaAtentamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Termo de Responsabilidade.
        /// </summary>
        public static string H1TermoResponsabilidade {
            get {
                return ResourceManager.GetString("H1TermoResponsabilidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opção:.
        /// </summary>
        public static string LabelCargo {
            get {
                return ResourceManager.GetString("LabelCargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPF:.
        /// </summary>
        public static string LabelCPF {
            get {
                return ResourceManager.GetString("LabelCPF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de Nascimento:.
        /// </summary>
        public static string LabelDataNascimento {
            get {
                return ResourceManager.GetString("LabelDataNascimento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail:.
        /// </summary>
        public static string LabelEmail {
            get {
                return ResourceManager.GetString("LabelEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endereço:.
        /// </summary>
        public static string LabelEndereco {
            get {
                return ResourceManager.GetString("LabelEndereco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado Civil:.
        /// </summary>
        public static string LabelEstadoCivil {
            get {
                return ResourceManager.GetString("LabelEstadoCivil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filhos menores 18 anos:.
        /// </summary>
        public static string LabelFilhosMenores {
            get {
                return ResourceManager.GetString("LabelFilhosMenores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Necessita tratamento especial?.
        /// </summary>
        public static string LabelNecessitaTratamento {
            get {
                return ResourceManager.GetString("LabelNecessitaTratamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome:.
        /// </summary>
        public static string LabelNome {
            get {
                return ResourceManager.GetString("LabelNome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Possui alguma deficiência?.
        /// </summary>
        public static string LabelPossuiDeficiencia {
            get {
                return ResourceManager.GetString("LabelPossuiDeficiencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RG:.
        /// </summary>
        public static string LabelRG {
            get {
                return ResourceManager.GetString("LabelRG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefones:.
        /// </summary>
        public static string LabelTelefones {
            get {
                return ResourceManager.GetString("LabelTelefones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declaro que tomei conhecimento, estou de acordo e atendo as exigências e normas contidas no Edital deste certame e estou ciente de que a falsidade ou inexatidão das afirmativas, declarações e documentações, bem como irregularidades no certame, permitirá a anulação a qualquer tempo da minha inscrição, prova ou contratação, eliminando-me do certame e cancelando todos os atos decorrentes da inscrição..
        /// </summary>
        public static string LabelTermoResponsabilidade {
            get {
                return ResourceManager.GetString("LabelTermoResponsabilidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ao clicar em CONFIRMAR INSCRIÇÃO assumo a responsabilidade pelas informações aqui contidas, como aceito as normas que regem este certame..
        /// </summary>
        public static string LabelTermoResponsabilidadeClique {
            get {
                return ResourceManager.GetString("LabelTermoResponsabilidadeClique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não.
        /// </summary>
        public static string OpcaoNao {
            get {
                return ResourceManager.GetString("OpcaoNao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sim.
        /// </summary>
        public static string OpcaoSim {
            get {
                return ResourceManager.GetString("OpcaoSim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLIQUE EM &apos;CONFIRMAR INSCRIÇÃO&apos; PARA FINALIZAR SEU CADASTRO OU &apos;VOLTAR&apos; PARA FAZER ALGUMA CORREÇÃO.
        /// </summary>
        public static string SubSubTituloTela {
            get {
                return ResourceManager.GetString("SubSubTituloTela", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONFIRA ATENTAMENTE SEUS DADOS.
        /// </summary>
        public static string SubTituloTela {
            get {
                return ResourceManager.GetString("SubTituloTela", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmação de Inscrição - {0}.
        /// </summary>
        public static string TituloTelaConfirmacao {
            get {
                return ResourceManager.GetString("TituloTelaConfirmacao", resourceCulture);
            }
        }
    }
}
