//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TGV.IPEFAE.Web.Resources.Admin.Estagio {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EstagioCSV {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EstagioCSV() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TGV.IPEFAE.Web.Resources.Admin.Estagio.EstagioCSV", typeof(EstagioCSV).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BAIRRO.
        /// </summary>
        public static string HeaderBairro {
            get {
                return ResourceManager.GetString("HeaderBairro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CEP.
        /// </summary>
        public static string HeaderCEP {
            get {
                return ResourceManager.GetString("HeaderCEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CIDADE.
        /// </summary>
        public static string HeaderCidade {
            get {
                return ResourceManager.GetString("HeaderCidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMPLEMENTO.
        /// </summary>
        public static string HeaderComplemento {
            get {
                return ResourceManager.GetString("HeaderComplemento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPF.
        /// </summary>
        public static string HeaderCPF {
            get {
                return ResourceManager.GetString("HeaderCPF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CTPS_Nº.
        /// </summary>
        public static string HeaderCTPSNro {
            get {
                return ResourceManager.GetString("HeaderCTPSNro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CTPS_SÉRIE.
        /// </summary>
        public static string HeaderCTPSSerie {
            get {
                return ResourceManager.GetString("HeaderCTPSSerie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATA_EXP_RG.
        /// </summary>
        public static string HeaderDataExpedicaoRG {
            get {
                return ResourceManager.GetString("HeaderDataExpedicaoRG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATA_NASCIMENTO.
        /// </summary>
        public static string HeaderDataNascimento {
            get {
                return ResourceManager.GetString("HeaderDataNascimento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-MAIL.
        /// </summary>
        public static string HeaderEmail {
            get {
                return ResourceManager.GetString("HeaderEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENDEREÇO_Nº.
        /// </summary>
        public static string HeaderEnderecoNro {
            get {
                return ResourceManager.GetString("HeaderEnderecoNro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESTADO.
        /// </summary>
        public static string HeaderEstado {
            get {
                return ResourceManager.GetString("HeaderEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEL_01.
        /// </summary>
        public static string HeaderFone01 {
            get {
                return ResourceManager.GetString("HeaderFone01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEL_02.
        /// </summary>
        public static string HeaderFone02 {
            get {
                return ResourceManager.GetString("HeaderFone02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INÍCIO_CURSO.
        /// </summary>
        public static string HeaderInicioCurso {
            get {
                return ResourceManager.GetString("HeaderInicioCurso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOME.
        /// </summary>
        public static string HeaderNome {
            get {
                return ResourceManager.GetString("HeaderNome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOME DO CURSO.
        /// </summary>
        public static string HeaderNomeCurso {
            get {
                return ResourceManager.GetString("HeaderNomeCurso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOME DA ESCOLA.
        /// </summary>
        public static string HeaderNomeEscola {
            get {
                return ResourceManager.GetString("HeaderNomeEscola", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RG.
        /// </summary>
        public static string HeaderRG {
            get {
                return ResourceManager.GetString("HeaderRG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEMESTRE_CURSO.
        /// </summary>
        public static string HeaderSemestreCurso {
            get {
                return ResourceManager.GetString("HeaderSemestreCurso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TÉRMINO_CURSO.
        /// </summary>
        public static string HeaderTerminoCurso {
            get {
                return ResourceManager.GetString("HeaderTerminoCurso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIPO DE ENSINO.
        /// </summary>
        public static string HeaderTipoEnsino {
            get {
                return ResourceManager.GetString("HeaderTipoEnsino", resourceCulture);
            }
        }
    }
}
