//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TGV.IPEFAE.Web.Resources.Admin.Estagio {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TGV.IPEFAE.Web.Resources.Admin.Estagio.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gerar CSV.
        /// </summary>
        public static string BotaoCSV {
            get {
                return ResourceManager.GetString("BotaoCSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gerar PDF.
        /// </summary>
        public static string BotaoPDF {
            get {
                return ResourceManager.GetString("BotaoPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pesquisar.
        /// </summary>
        public static string BotaoPesquisar {
            get {
                return ResourceManager.GetString("BotaoPesquisar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clique para visualizar mais estagiários.
        /// </summary>
        public static string CliqueVisualizar {
            get {
                return ResourceManager.GetString("CliqueVisualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curso.
        /// </summary>
        public static string ColunaCurso {
            get {
                return ResourceManager.GetString("ColunaCurso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string ColunaNome {
            get {
                return ResourceManager.GetString("ColunaNome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sem/Ano.
        /// </summary>
        public static string ColunaSemAno {
            get {
                return ResourceManager.GetString("ColunaSemAno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Situação.
        /// </summary>
        public static string ColunaSituacao {
            get {
                return ResourceManager.GetString("ColunaSituacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefone.
        /// </summary>
        public static string ColunaTelefone {
            get {
                return ResourceManager.GetString("ColunaTelefone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atualização.
        /// </summary>
        public static string ColunaUltimaAtualizacao {
            get {
                return ResourceManager.GetString("ColunaUltimaAtualizacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semestre / Ano.
        /// </summary>
        public static string LabelFiltroAno {
            get {
                return ResourceManager.GetString("LabelFiltroAno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cidade.
        /// </summary>
        public static string LabelFiltroCidade {
            get {
                return ResourceManager.GetString("LabelFiltroCidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPF.
        /// </summary>
        public static string LabelFiltroCPF {
            get {
                return ResourceManager.GetString("LabelFiltroCPF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curso.
        /// </summary>
        public static string LabelFiltroCurso {
            get {
                return ResourceManager.GetString("LabelFiltroCurso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string LabelFiltroNome {
            get {
                return ResourceManager.GetString("LabelFiltroNome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Situação.
        /// </summary>
        public static string LabelFiltroSituacao {
            get {
                return ResourceManager.GetString("LabelFiltroSituacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Considerar.
        /// </summary>
        public static string LabelFiltroVisualizacao {
            get {
                return ResourceManager.GetString("LabelFiltroVisualizacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gerando CSV ....
        /// </summary>
        public static string MensagemGerarCSV {
            get {
                return ResourceManager.GetString("MensagemGerarCSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gerando PDFs ....
        /// </summary>
        public static string MensagemGerarPDF {
            get {
                return ResourceManager.GetString("MensagemGerarPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pesquisando ....
        /// </summary>
        public static string MensagemPesquisando {
            get {
                return ResourceManager.GetString("MensagemPesquisando", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhum estagiário encontrado.
        /// </summary>
        public static string NenhumEstagiarioEncontrado {
            get {
                return ResourceManager.GetString("NenhumEstagiarioEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estagiando.
        /// </summary>
        public static string OptionEstagiando {
            get {
                return ResourceManager.GetString("OptionEstagiando", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não Estagiando.
        /// </summary>
        public static string OptionEstagiandoNao {
            get {
                return ResourceManager.GetString("OptionEstagiandoNao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todos.
        /// </summary>
        public static string OptionEstagiandoTodos {
            get {
                return ResourceManager.GetString("OptionEstagiandoTodos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocultos.
        /// </summary>
        public static string OptionOcultos {
            get {
                return ResourceManager.GetString("OptionOcultos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visíveis.
        /// </summary>
        public static string OptionVisiveis {
            get {
                return ResourceManager.GetString("OptionVisiveis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Currículo.
        /// </summary>
        public static string TitleEditar {
            get {
                return ResourceManager.GetString("TitleEditar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista de Estagiários.
        /// </summary>
        public static string TituloTela {
            get {
                return ResourceManager.GetString("TituloTela", resourceCulture);
            }
        }
    }
}
